### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by heyepic** [hufman/AndroidAutoIdrive#105]
I'm unable to install the latest release on my Pixel 4XL. Haven't had this issue in the past. Any idea? Allowed apk installs via Chrome and Files app as well as disabling Play Protect.

![Screenshot_20200825-094936](https://user-images.githubusercontent.com/12517908/91189727-691b7700-e6b8-11ea-8e90-e17a06f5663d.png)

**Comment by hufman** [comment]
Do you have the older version still installed? I used to provide both a debug and a release version, which only differ in what key was used for signing. I've changed it to only providing the release version, but perhaps you have the previous debug version installed, and the different signing key is blocking the upgrade. Try uninstalling and installing the new version and let me know if that helps!

**Comment by heyepic** [comment]
I removed the old version prior to installing.  I also tried installing via Files app (which has allow APK installs). Similar issue.

![Screenshot_20200825-095434](https://user-images.githubusercontent.com/12517908/91192744-e7c5e380-e6bb-11ea-8ce3-1a2af2ee4126.png)

**Comment by hufman** [comment]
:( Both my Galaxy S9 and Pixel2 worked, I'm not sure what else it could be. Can you watch the `adb logcat` output during the install process for any warning messages? When I had a differently-signed version on my Pixel 2, it showed the following message: `W/PackageManager: Package me.hufman.androidautoidrive signatures do not match previously installed version; ignoring!`

**Comment by heyepic** [comment]
This what you needed?

C:\Users\mattb\AppData\Local\Android\Sdk\platform-tools>adb -s install androidautoidrive-1.2.2-nomap-nonalytics-release.apk
Performing Streamed Install
adb: failed to install androidautoidrive-1.2.2-nomap-nonalytics-release.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package me.hufman.androidautoidrive signatures do not match previously installed version; ignoring!]

**Comment by hufman** [comment]
Oh neat! I didn't realize `adb install` showed the logs too, that's great.
That message says that an older AndroidAutoIdrive version is installed, how did you uninstall it before?

**Comment by heyepic** [comment]
Yea, I was surprised, too lol. Simply dragging the icon to uninstall. Apparently there are remnants kicking around?

**Comment by heyepic** [comment]
Figured it out - had to go to 'Apps' and click the elipsis, then 'Uninstall for all users'. Then it installed fine. Sorry for wasting your time - never had that happen before!
