### ISSUE TITLE
Smart Audiobook Player closes MediaSession when beginning playback

### ISSUE THREAD

**Issue by mfisher224** [hufman/AndroidAutoIdrive#110]
Appears in list of music apps in app but doesn't not appear on car and does not launch from app.

**Comment by hufman** [comment]
Hmmm interesting! I never got it to launch from the app, always requiring Smart Audiobook Player to be started manually. May I recommend the "Voice" app, which seems to be comparable and does support launching?

**Comment by mfisher224** [comment]
It's not just the launching. Doesn't seem to work at all even when launched
manually.

**Comment by hufman** [comment]
Weird! I confirmed with the Phone UI that it behaves very strangely: When the app commands Smart Audiobook Player to play, the current MediaSession is disconnected and a new one is created. By backing out to the main phone app and then tapping back into the Smart Audiobook Player icon, it then reconnects to this new MediaSession and resumes control.

A workaround which should work for you: After selecting Smart Audiobook Player in the car (which should trigger it to start playing again) go back a screen and push the same button to go back to the Audioplayer interface (whether picking the Smart Audiobook Player app from the App List screen, or from the main Media menu). This should trigger a reconnect and it should pick back up to show the cover art and playback progress like usual.

Thank you for reporting this bug! I'll work on it right away.

**Comment by mfisher224** [comment]
I will try again tomorrow, but since I updated yesterday Smart Audiobook
Player was not showing up in the car at all. Even though it is "enabled" on
the app.

**Comment by hufman** [comment]
It did take me a few tries for it to show up in the App List, I'll check into this too (it should pop up automatically as soon as the MediaSession is available).

**Comment by hufman** [comment]
[Dev build](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/545/545.1/app/build/outputs/apk/nomapNonalytics/release/androidautoidrive-1.2.2-22-d765f06-d765f06779eafa9d6b517266383808d6bdddc740-nomap-nonalytics-release.apk) with the fix

**Comment by mfisher224** [comment]
Hmm, still not working. Shows up in list of music apps but when I open it,
all options are greyed out. Doesnt show in car. This happens even when the
app is running. Screenshot attached

**Comment by hufman** [comment]
The screenshot didn't make it, but I'm incredibly curious about what you're seeing! Does Smart Audiobook Player start playing a book at least? Does the regular Smart Audiobook Player show a book being played too?

**Comment by mfisher224** [comment]
So, smart Audiobook Player works just fine as audio over bluetooth if I
launch it as normal from home screen. From within androidauto, it appears
in the overall list of music apps, but not in the "selected" apps list,
even though I have it turned on.  If I select it from the list, all options
are greyed out and it does not show that it's playing anything, even if it
actually is. And or course not showing up in the car.

**Comment by hufman** [comment]
Would you be able to post some pictures to the Github issue page? I'd love to see what you are seeing.

**Comment by mfisher224** [comment]
![Screenshot_20200913-184418](https://user-images.githubusercontent.com/58667784/93030467-4f06f180-f5f1-11ea-94f8-8da67ce244d8.jpg)
![Screenshot_20200913-184412](https://user-images.githubusercontent.com/58667784/93030470-4f9f8800-f5f1-11ea-947c-6cc55059a744.jpg)
![Screenshot_20200913-184406](https://user-images.githubusercontent.com/58667784/93030471-4f9f8800-f5f1-11ea-8805-308c4520842b.jpg)

**Comment by hufman** [comment]
Oh curious! I think you've found another bug: If you disable Notification Access in your System Settings after having granted it previously, my code doesn't detect it and doesn't show the button to request the permission again.
Try going into your phone's `Settings > Apps > Special App Access > Notification Access` or somewhere similar to see if AndroidAutoIdrive is allowed to read notifications, which is required to control Smart Audiobook Player. I'll work on fixing the code to show the button if the permission is not granted.

**Comment by mfisher224** [comment]
I think that fixed it. Will confirm later in the car. Thanks!
