### ISSUE TITLE
Album covers on Idrive 6 screen minimize mode

### ISSUE THREAD

**Issue by dimakaob** [hufman/AndroidAutoIdrive#123]
Hi! 
Is it possible to make the album cover show on the minimized screen? All i have now is just notes icon. 
I mean this screen mode. 
![Screen Shot 2017-06-19 at 8 31 59 PM](https://user-images.githubusercontent.com/72865270/95982305-a387d180-0e28-11eb-96cf-0ef410a4b764.jpg)

**Comment by hufman** [comment]
I believe this is tied to the same global coverart as the sidebar. Can you try installing the latest build, which supports logging in with the Spotify app resources?

If you have a new Spotify version installed on your phone (new enough that it doesn't support the BMW protocol anymore), it should detect this and automatically use this mode. If not, you'll have to enable Advanced Options by clicking the bottom tab bar, Configure the Music settings, and force enable Spotify mode.

Try that out and see if it works, or if you have any more questions!

**Comment by dimakaob** [comment]
Hello! Thank you for your answer.
I have the latest build of AA and the latest Spotify.
Sidebar is also empty for Spotify and Youtubemusic.
I have enabled the advanced options, but I can't find how to configure the
Music settings and force enable Spotify mode =((

ср, 14 окт. 2020 г., 17:37 Walter Huf <notifications@github.com>:

**Comment by hufman** [comment]
Hmm I apologize, I meant the latest build linked on the main page, not the latest release. [Click here](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/androidautoidrive-latest-master-nomap-nonalytics-release.apk) to download it.

This new version will have an extra option in the Music settings. However, since you have the latest Spotify, it _shouldn't_ be necessary to enable it.
![Screenshot_20201014-082057_AndroidAutoIdrive](https://user-images.githubusercontent.com/1592375/96010430-a073ed80-0df6-11eb-913e-9b3238ff57d1.jpg)

Try that out and see if you find the new option!

**Comment by dimakaob** [comment]
Got it! Thanks!
I'll try it and tell you how it is! =)

ср, 14 окт. 2020 г., 18:27 Walter Huf <notifications@github.com>:

**Comment by MLiv79** [comment]
Hi walter I can't see those options too with the linked release, it's 
necessary the latest spotify release to view it?

In data 14 ottobre 2020 17:27:12 Walter Huf <notifications@github.com> ha 
scritto:

**Comment by dimakaob** [comment]
Oh, BTW, is is also a reason I have two audioplayers in the list?

ср, 14 окт. 2020 г., 18:27 Walter Huf <notifications@github.com>:

**Comment by MLiv79** [comment]
Ok now i can see them, i haven't enable advanced settings thanks

In data 14 ottobre 2020 18:00:46 Walter Huf <notifications@github.com> ha 
scritto:

**Comment by dimakaob** [comment]
Funny thing, but I have only the new connected app. I deleted the classic
one once the new app was released. And the two audioplayers really pisses
me off =D

ср, 14 окт. 2020 г., 19:00 Walter Huf <notifications@github.com>:

**Comment by hufman** [comment]
Check in your Apps list, it may be that it only uninstalled "for your user" but not from the phone itself?
Does this other Audioplayer icon open the regular Connected Classic Audioplayer or just not work?

**Comment by dimakaob** [comment]
It does nothing. Just not work.
And I checked the apps list. Only the new connected app. Maybe I should
reinstall it..

ср, 14 окт. 2020 г., 19:26 Walter Huf <notifications@github.com>:

**Comment by hufman** [comment]
That's very strange indeed!
However: Does the Spotify mode work and show cover art on the main screen? I'm curious about why it wasn't automatically switching to Spotify mode, did you change anything to get it to work besides the checkbox?

**Comment by dimakaob** [comment]
I don't know =) I just press the second audioplayer and I see Spotify or
You Music.
on the main screen I see the covers, yes.
Anyway, when I get in the car I'll make some pics and show you what I got
there.


ср, 14 окт. 2020 г., 19:42 Walter Huf <notifications@github.com>:

**Comment by dimakaob** [comment]
Wow! It works!!! Hooray! =D
I see the covers, and just one audioplayer is visible.
Thank you so much for your help!
Now I don't need to buy iPhone to see the covers.
Once again, thank you!

ср, 14 окт. 2020 г., 19:42 Walter Huf <notifications@github.com>:

**Comment by hufman** [comment]
Yaaay glad to help! Can you tell me what all you changed to get it working? They latest build is supposed to detect it automatically, so I want to fix any bugs in this logic.
Thank you again, I hope you enjoy it!

**Comment by dimakaob** [comment]
Actually, I've just did what you told me. I downloaded the AA app from your
link and checked this "Always appear as Spotify..". That's all =)

P.S. Can you tell me what is Auto Focus?

ср, 14 окт. 2020 г., 20:57 Walter Huf <notifications@github.com>:

**Comment by hufman** [comment]
If you wouldn't mind, when you get a chance, could you uncheck the "Always appear as Spotify" and reconnect to the car, to confirm whether the automatic mode detection works?

"Audio Focus" is the concept of what music source the car is currently listening to and playing out through the speakers. Not just the physical audio source, the car also tracks some extra functionality along with the focus. Specifically relevant here, the car differentiates between the audio focus of the Bluetooth Music and the audio focus of a Phone App over Bluetooth. Even though the music is coming from the same actual source (Bluetooth A2DP), the car will only enable extra functionality for the current audio focus: global coverart, instrument cluster, sending the hardware back/next buttons from the dashboard, sending pause events when a phone call starts or the mute button is pushed, and so on. Only while this app has the current Audio Focus can the app set the coverart and the instrument cluster information.

Technically, the remote app protocol supports creating an audio context over USB (when the app is running in USB mode), and the car will dutifully listen to the USB port for music when told to. However, Android removed that specific USB audio protocol, and so the car never hears any music over the cable. So, this app only asks for audio context over a Bluetooth connection, and relies on the user to manually select the Bluetooth input when it is running over USB.

Hope that answered your question in a clear way! I love talking about all I've learned on this project, so thank you for asking for more information :)

**Comment by dimakaob** [comment]
Hello again! 

Thank you for your detailed and interesting answer. I read it with pleasure. And i turned on this Audio Focus. I guess it is no harm %)

So i unchecked the "Always appear as Spotify". Works okey so far. Will try again later. =)

Btw, it seems like i can use Google maps here? Or not? If so, how to do it?

**Comment by hufman** [comment]
That's great to hear! You shouldn't need the Audio Focus checkbox either, because Audio Focus is automatically enabled when running over Bluetooth.

There is code that supports embedding an Android MapView (which uses the same Maps tile appearance) and querying the Google Places API and Directions API, but it is not the true Google Maps experience. I'm also not satisfied with the performance either (1fps over Bluetooth, and sets your phone on fire with the 100% cpu usage), so I can't recommend that you go through the effort to build a maps-enabled version and end up disappointed :)

**Comment by dimakaob** [comment]
Got it! 
Thank you for the answers.
