### ISSUE TITLE
Support autostarting playback on MediaSession apps

### ISSUE THREAD

**Issue by hufman** [hufman/AndroidAutoIdrive#132]
Currently it only supports resuming playback on apps that can be directly launched. However, if the media session is currently running, it should be able to resume playback from that app.

**Comment by hufman** [comment]
[This branch](https://github.com/hufman/AndroidAutoIdrive/tree/am_split) (and [build](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/androidautoidrive-latest-am_split-nomap-nonalytics-release.apk)) includes an early fix.

**Comment by bogdan-calapod** [comment]
Fix confirmed for YouTube Music :D
