### ISSUE TITLE
Auto-increase phone volume when connected to the car

### ISSUE THREAD

**Issue by bogdan-calapod** [hufman/AndroidAutoIdrive#133]
I frequently find myself maxing out the media volume on the phone when connecting to the car. I used to have a "hack" with [Automate](https://play.google.com/store/apps/details?id=com.llamalab.automate) a while back, but it would be nice if AndroidAutoIdrive could do this by default :D

**Comment by hufman** [comment]
That's a good idea! I had considered it a while ago, but recently I've added code to check if the phone is actually connected over Bluetooth Music to a car which will make me a lot more confident about changing the system volume.
