### ISSUE TITLE
Add usage tips to the phone ui

### ISSUE THREAD

**Issue by hufman** [hufman/AndroidAutoIdrive#143]
There are some handy ways to add the app to the car's shortcut buttons, and some things (legacy Audioplayer on ID4 cars, Notifications, Google Assistant) are much more useful in this way. These shortcut buttons are a little tricky though, and users might not know that they need to save them while the destination icon is selected (eg, while the Audioplayer menu icon is highlighted, not while they are in the app)
As part of the Phone UI refresh #81, there should be little tip popups suggesting the recommended shortcuts. Critically, there should be an image showing, for example, the Audioplayer app selected in the car with a juxtaposed picture showing a (ghost-like?) finger pressing (and somehow indicating a long press) the shortcut button bar.

**Comment by hufman** [comment]
An early version is [posted and built](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/androidautoidrive-latest-tips-nomap-sentry-release.apk), check it out!

**Comment by fabssor** [comment]
Hi hufman, had a look at your build. I think it is a nice starting point here are some notes from me:

- Wouldn't it be nice to have the Tips hide behind a question mark icon for each side? Something like this: 
![Screenshot_20210425-131124](https://user-images.githubusercontent.com/30718590/115991369-497e7a80-a5c8-11eb-9952-44624f775005.jpg)
This could trigger the Tips and Tricks. For now, I think it is cluttering the pages if they are showing always.
May the tips could then show the first time one is loading each page, Afterwards, they are hidden behind this icon.
- Maybe an indicator (those little dots) beneath the picture would help to show that you are able to slide left and right for more information. See an example for what I mean here: [LINK](https://cdn.dribbble.com/users/72535/screenshots/2578447/pagination-collection-by-jardson-almeida.gif)

Greets!

**Comment by hufman** [comment]
Good suggestions! I moved the tips to be behind a toggle button, and added the little bar of dots below them. I hoped that the previous/next slides would appear at the edge of a screen as a hint, but your screenshot shows that it isn't showing for you. By making the tips show only on demand, it means I don't need to worry too much about keeping the vertical height low, which gives the ability to add that tab bar.

**Comment by fabssor** [comment]
So had a Look again and I think it has now better visibility.
Still some weird things:

1. I personally do not like the frame in frame look.
2. See Screenshots: the first one Shows the next tile on the edge. The second one not
![Screenshot_20210426-203727.jpg](https://user-images.githubusercontent.com/30718590/116134105-d19b7780-a6cf-11eb-90ad-ec2d3031e110.jpg)
![Screenshot_20210426-203738.jpg](https://user-images.githubusercontent.com/30718590/116134080-c5afb580-a6cf-11eb-957a-e7afa0bcca72.jpg)

**Comment by hufman** [comment]
Ah, thank you for pointing it out! I fixed the overflow issue on the Overview tab, and removed the double frame.

**Comment by fabssor** [comment]
So I am a little bit nitpicking here, sorry for that😃 

Some things which can be changed in the future:

- First time opening the application. The first tip shows only one tile. See the screenshot below. After navigating again to this page both tiles are shown as expected. See the first screenshot and the second one for comparison.
- Some images are not centered. See both screenshots.

![Screenshot_20210427-092403](https://user-images.githubusercontent.com/30718590/116202359-c6316600-a73a-11eb-94bf-1e726d3fafb2.jpg)

![Screenshot_20210427-092412](https://user-images.githubusercontent.com/30718590/116202460-e9f4ac00-a73a-11eb-8890-cb34198f6010.jpg)

Greetings! :)

**Comment by hufman** [comment]
No worries, I appreciate the feedback! I know I won't be looking at the tips very much, so I appreciate an outsiders' view!!
I fixed the first-view behavior, and I hope I fixed the centering and size issues, my emulator has a different size than your phone it seems. I do see that there's a crash on screen rotation, so I have to look into that next.

**Comment by hufman** [comment]
Crash fixed!

**Comment by fabssor** [comment]
Had a look again. Looks pretty clean now!
Some Things: 
In the home page the first tile ist missing the text. The second tiles text is cut of. See the Screenshots!
![Screenshot_20210428-221840.jpg](https://user-images.githubusercontent.com/30718590/116467491-06decb80-a870-11eb-9321-4a41e2d0f158.jpg)![Screenshot_20210428-221835.jpg](https://user-images.githubusercontent.com/30718590/116467506-0ba37f80-a870-11eb-8bc1-fd9a3693d34b.jpg)

Maybe in the music page a additional tile with a tip to turn off the battery optimzation for the music Apps would also be great!

Also noticed this Bug in the music page: 
1. If you Open the Tips.
2. Then click on eg. Spotify.
3. Navigate Back (with the Android Back Action)
4. Close the Tips.
5. The music App list will stay collapsed like in the screenshots.
![Screenshot_20210428-222538.jpg](https://user-images.githubusercontent.com/30718590/116468624-62f61f80-a871-11eb-812a-6abb7e38ba87.jpg)

**Comment by hufman** [comment]
Ok, I think I figured out a way to autosize the tips, so it should be generic for any phone now. I also fixed the music appslist resize logic like you found.

**Comment by fabssor** [comment]
Very cool! Looks all good now! 😀

**Comment by hufman** [comment]
Great! :D
