### ISSUE TITLE
Feature Request: Show Messages on Display ID5 / 6 / 7

### ISSUE THREAD

**Issue by christiancloudical** [hufman/AndroidAutoIdrive#148]
Hey ho,

Is there any way, to implement a "proper" notification on CD after ID4?
Do you work on that feature?
If it is not possible to have something else than the "ping", than that ticket can be closed again ;)

Greetings,

Christian

P.S.: Radio Bob and accessing via shortcut works like a charm :D

**Comment by hufman** [comment]
Good morning!
I am collecting ideas in #99, I think the most promising approach will be to figure out how Mini FindMate works when it adds a new message to the car's Notification Center. This adds an icon in the top system bar, and the Notification Center would allow for clicking into the application. I haven't yet experimented with this API yet, but it should be relatively straight forward once I find an official application to log in as which supports this API.

**Comment by christiancloudical** [comment]
Oh sorry, I missunderstood that issue - will close that one as dublicate
