### ISSUE TITLE
bmw idrive 6 - Media split view Spotify icon

### ISSUE THREAD

**Issue by ronniebadmf** [hufman/AndroidAutoIdrive#161]
using version 1.2.2.
on BMW idrive 6 - the media split view does not display the Spotify song/album cover. Would contribute to improving the UX.
thanks!

**Comment by hufman** [comment]
Good news! This feature #59 is already implemented! It just hasn't made it to a new full release yet.
Try out the [latest dev build](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/androidautoidrive-latest-master-nomap-sentry-release.apk) to see all the newest features. Make sure you have the latest Spotify installed and that you are running the app over Bluetooth and not USB, and it should just work!
Try it out and let me know how it goes!

**Comment by ronniebadmf** [comment]
Hi Walter. It works like a charm. The pictogram displays and the overall
experience got better. I owe you another coffee. Thanks for bringing back
the joy of using Spotify in the car.
Cheers
Dragoș

**Comment by hufman** [comment]
Thank you so much for the kind words!

**Comment by ronniebadmf** [comment]
Thumbs up Walter!
Here's my post on the spotify community:

Cheers, Dragos

[image: image.png]
