### ISSUE TITLE
Pandora Playlist and Station Creation and Searching are not enabled

### ISSUE THREAD

**Issue by Kay0002** [hufman/AndroidAutoIdrive#178]
Enhancement: Currently unable to view playlists or search for artists in Pandora. It would be great if Pandora had full functionality, similar to Spotify and iHeartRadio.

Build Version: 1.2.2-297-b3164dc

btw this is an awesome app! Thank you all :)

**Comment by hufman** [comment]
Pandora does not grant browse functionality to AndroidAutoIdrive through the normal Android API. I looked for a specific Pandora API, but they only seem to provide an API for building your own Pandora player as opposed to controlling the existing Pandora client. I'm sorry, this request does not appear to be possible at the moment. If a method of control is figured out, it could be implemented as a separate MusicAppController like Spotify's custom API.
Thank you for the compliments though!

**Comment by Kay0002** [comment]
Ok, I appreciate you for considering this. I do hope it's compatible in the future. Thank you!
