### ISSUE TITLE
Places API - error

### ISSUE THREAD

**Issue by jezikk82** [hufman/AndroidAutoIdrive#180]
Hi, in the GMAP treat I mentioned about 3 months ago that after one of the updates search and directions stopped working. 
I checked the Google Cloud Platform console and see that I have 100% of the api calls google.places.Autocomplete.Http ended with error from group 4xx. 
I double checked the permissions and my API have access to Maps SDK (works fine), Places API (problem with calls), Directions API (0 calls as no results from places).

Can someone confirm if that works in current version? 
@hufman Any suggestions how to debug it ?

**Comment by 6i6i** [comment]
I also got MAPS now working, but the search is not working.
I have the same error, that all google.places.Autocomplete.Http requests ended with error of the group 4xx.

**Comment by hufman** [comment]
Hmmm it works for me.. I do see the api requests come in through the Places API:
![image](https://user-images.githubusercontent.com/1592375/107158195-38b15780-693d-11eb-9c85-b7b62893b04f.png)

I wonder if the Places SDK is also needed? Here are my key's restrictions (I don't have any application restrictions, by app or IP or anything):
![image](https://user-images.githubusercontent.com/1592375/107158148-0273d800-693d-11eb-9db1-ad73d3910b4c.png)

I tried removing Places SDK from my key, waiting a bit, and trying again, but it still seemed to work.. Dunno if I just didn't wait long enough to be a valid test or if it actually isn't needed :\
Does it work if you grant it access to all APIs (`Don't destrict key`)?

**Comment by 6i6i** [comment]
Hello,

I have not restricted the KEY at all in the developer console:
![grafik](https://user-images.githubusercontent.com/6044026/107207051-1fbdaa80-6a00-11eb-9d14-d9ab6dccf04c.png)

**Comment by jezikk82** [comment]
I have the same APIs&SDK as you @hufman and without any restrictions. Unfortunately I don't work.

The navi tab you added in the app is working

**Comment by hufman** [comment]
And just to confirm, is Billing set up and working? It looks like Maps on mobile are free, while Places and Routing have a price. I think this changed a year ago though, so maybe a credit card on file expired?
Have you seen any suspicious errors from `adb logcat` after trying to search?

**Comment by hufman** [comment]
[Another user](https://github.com/hufman/AndroidAutoIdrive/discussions/225#discussioncomment-426657) encountered the same problem and enabling billing fixed the problem, can you confirm if billing is set up for you?
