### ISSUE TITLE
Listening to Spotify Podcasts show untranslated Strings in Action menu

### ISSUE THREAD

**Issue by 6i6i** [hufman/AndroidAutoIdrive#181]
When listening to a podcast in Spotify the Action sub menu has entries with Icons to seek 15 seconds for and backward. The labels of the entries are with _ (i think not translated?).:

![20210107_173736](https://user-images.githubusercontent.com/6044026/103919818-cae0f880-5110-11eb-85eb-451913357780.jpg)

**Comment by hufman** [comment]
Good catch! Those official actions from Spotify are indeed manually translated by this app to show in IDrive (while Android Auto itself only shows the icons), so I will add translations for these 15sec seek actions. Thank you so much for reporting this!
