### ISSUE TITLE
Add screen with weather forecast

### ISSUE THREAD

**Issue by 6i6i** [hufman/AndroidAutoIdrive#194]
One additional thing that came to my mind was that it would be cool to have some simple weather forecast screen in the idrive menu to check how it will be tomorrow (or 2,3 days).

Some nice Icons would be great here.

In a first step it would be enough to add the location in the app manually.

**Comment by LACNR** [comment]
If you have your Connected Drive Services activated, you can check out the weather forecast for any location and 7 days ahead, also see the a temprature, rain and cloudy radar live forecast for the day.

Aside that, if you have your weather apps on your phone and its notification enabled you can check out the weather when using AndroidAutoiDrive by going to the Notification menu in your iDrive.

**Comment by 6i6i** [comment]
Yes I know that. It was working before in the connected drive services, but i think as my car only has 3G connection this was disabled in my country already. So It does not work any more.

Yes that I also discovered with the notification. 
I just tought it would be nice to have a "Connected Drive Services" like Weather information for the users, that do not have BMW Online or where it does not work any more.

**Comment by hufman** [comment]
That's a good idea! I hadn't thought that the built-in weather app could be removed, and I suppose some cars don't include it at all. I've added it to the [list of addon ideas here](https://github.com/hufman/IDriveConnectAddons).
Hopefully the workaround with the phone Notifications works well enough in the meantime. Thank you for the idea!
