### ISSUE TITLE
Spotify Web API causes app crashes without internet connection

### ISSUE THREAD

**Issue by daniel1v** [hufman/AndroidAutoIdrive#195]
When I start Spotify playback from car and don't have an Internet connection on the phone, AndroidAutoIdrive crashes after a few seconds and the whole connection stops to work. After starting AndroidAutoIdrive manually, it works again, but when I start Spotify playback, it happens again.

A workaround was, to reset the app via Android settings and to not authenticate Spotify Web API. Since I did this, it works perfectly again. As soon as I do the authentication,  it happens again. So I think the crash is somehow related to the Spotify Web API not being able to connect to the web.

**Comment by hufman** [comment]
Thank you so very much for reporting this! Currently the API is only used to load the queue's cover art when playing the Liked Songs playlist. We next plan to support searching through this API, and so thank you so much for reporting this bug before it breaks this bigger feature!

**Comment by daniel1v** [comment]
Nothing to thank for. Keep up the great work. 😀
