### ISSUE TITLE
Spotify browse

### ISSUE THREAD

**Issue by KdiKomunismo** [hufman/AndroidAutoIdrive#202]
First of all hufman many many thanks for your great work! I was already looking for a car stereo swap when I came across your project and decided to keep the original one.

I'm sorry to bother with an issue that maybe has shown up a million times, but I couldn't find any solution browsing the issues. 

I have a 2018 f36, with the small screen ID6.
I compiled the app following all the instructions (and with the help of a proper programmer) but I never got Spotify browse to work.
First I tried with the old Spotify version, but didn't work, then I tried with the last one and now coverarts are showing up but still no luck with browsing.
I keep getting the message
"explicit user authorisation required..." 
even if the Spotify entry states 
"fully controllable, browsable and searchable" (in Italian) 

In the notification bar I get a message
"Spotify connections
Connection of androidautoidrive ongoing) 
but pressing it does nothing...

Here are a couple screenshots

https://photos.app.goo.gl/rmBnTiMKbWdTFquLA

**Comment by masteralarm** [comment]
If you want to build and use the app by yourself, you need to also configure everything accordingly in your spotify developer dashboard, as described [here ](https://github.com/hufman/AndroidAutoIdrive#build-instructions)in the README. Did you already do this?

I suppose it would be easier for you to just use the current nightly build as linked also in the README:
[nightly build (Sentry)](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/androidautoidrive-latest-master-nomap-sentry-release.apk)
Then you don't need to follow any further steps.

**Comment by hufman** [comment]
Good morning!
Installing the nightly build would definitely be the easiest! But I'd like to figure out the problem too.
The error you see "Explicit user authorization required" is because the Music Apps screen tries to connect to Spotify with any existing privileges, without requesting a permission prompt. The `Concedi` button should tell Spotify to open a permission prompt to grant access to control it. What does the button do when you click it?
The Browseable status might be from when the earlier version of Spotify was installed, perhaps.. the cache is very sticky.

**Comment by KdiKomunismo** [comment]
First of all, thanks for the speed of the reply!
The nightly build actually solved everything and now it works like a charm!

About @hufman question, the Concedi button did make the error show up, and nothing more.
I have to admit I don't remember if the new version of Spotify prompted me to give permission, but I'm pretty sure that it did at least with the old version (which didn't work too).

Unfortunately I'm not able to make any further test, because I happen to have changed my laptop without bringing Android Studio from the old one, and I don't even have the apk I generated...

**Comment by hufman** [comment]
Hmmm thank you for the information! I'll keep watching for any other similar problems!
I'm glad the nightly build lets you enjoy the latest features without needing to compile it yourself :)

**Comment by GijsTimmers** [comment]
I am having the exact same issue. Attaching a video to show you what happens. It seems like a Spotify authorization popup is

https://user-images.githubusercontent.com/972314/108650353-a920b280-74bf-11eb-9217-5e2cfcd48583.mp4

 spawned which crashes immediately.

**Comment by GijsTimmers** [comment]
Update: disabling wifi and enabling data connection made the spotify authorization popup show correctly.
