### ISSUE TITLE
Music plays from phone instead from BMW

### ISSUE THREAD

**Issue by itafraji** [hufman/AndroidAutoIdrive#207]
Hi, Thank you very much for the great job on this app. I tested it quickly in NBT and it seems to work.
Maybe didn't understood well but what I have to do is to connect with bluetooth and USB from ConnectedDrive menu. 
If I don't connect with bluetooth I'm able to start and contrill applications, but the sound is coming from my phone and not from the car. With both USB and bluetooth it is OK.

Did I miss something or this is expected way to work in a car with iDrive 4 (it is F10 2015 LCI).

Thanks again !

**Comment by hufman** [comment]
Thank you so much for the kind words!
Yes, that is the expected behavior with ID4. When I had an ID4 car, I found it useful to save the Audioplayer to a dashboard shortcut button, and I miss the notification popup feature from the car.
I'm glad you like it!
