### ISSUE TITLE
IHeartRadio not playing automatically on connection

### ISSUE THREAD

**Issue by Kay0002** [hufman/AndroidAutoIdrive#208]
Hi,

I just updated the version of the app that I'm using (was using a the latest incremental build that I downloaded in Sept or Oct 2020).  Currently using Build Version: 1.2.2-359-f65cd5e Feb 7, 2021 9:00:06 PM.

In the build from last Sept/Oct IHeartRadio automatically was playable from Idrive without me having to manually start the app. Now with the latest build i cannot launch IHeartRadio from Idrive. 

Also the normal IHeartRadio icon in Idrive is just blank when I select it now. However the 2nd IHeartRadio icon (that's appears with a circle around it) plays once i launch the app on my phone, but I cannot browse my stations or artists through this icon.

Please help!

**Comment by Kay0002** [comment]
both app icons
![20210217_093403](https://user-images.githubusercontent.com/77034203/108301781-b6146d80-7170-11eb-9954-a319fa6b1581.jpg)

The iHeartRadio icon that used to auto launch is now blank...
![20210217_093417](https://user-images.githubusercontent.com/77034203/108301850-d0e6e200-7170-11eb-8255-cb63304b8288.jpg)


The other iHeartRadio app in which I cannot browse
![20210217_093431](https://user-images.githubusercontent.com/77034203/108301877-de9c6780-7170-11eb-960a-b3a10f786891.jpg)

**Comment by hufman** [comment]
Whoa, that's surprising! I've never seen iHeartRadio be controllable ever!
As a test, you could see if this [build from November](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/848/848.1/nomapNonalytics/release/androidautoidrive-1.2.2-156-aa2f966-aa2f9661c401a7cd8c76a9e80346daa5830e3648-nomap-nonalytics-release.apk) still works, it's the earliest nightly build I found on the build server. If you still have the same phone, the old apk might also be in your Downloads folder, I know I'm bad about clearing my phone's downloads.
Funny enough, I was just showing someone on Monday how iHeartRadio's BMW app is so rock solid, and it uses a Foreground Notification to keep it from getting killed by Android, and of course it failed the one time I showed it just like the picture you show. I see iHeartRadio was updated recently, I wonder if a [previous version](https://apkpure.com/iheartradio-radio-podcasts-music-on-demand/com.clearchannel.iheartradio.controller/versions) might still work.

I sincerely appreciate the comprehensive pictures showing the problem! I don't know how to help about the iHeartRadio browsing functionality, I've never seen it let AndroidAutoIdrive connect to launch it or to browse it. I suspect the official BMW iHeartRadio may have broken during a recent upgrade, and I'd be interested to see what you find with an older version.

**Comment by Kay0002** [comment]
Yup, it worked flawlessly since I downloaded your app! I actually had slightly more functionality than the Spotify, because I could create new stations by entering an artist's name or song in iDrive. You did an excellent job with this iDrive app, it's been very useful (I use it daily). 

I hadn't considered iHeartRadio may have messed something up 🤦🏽‍♀️. I'll give your suggestions a try this week and report back.

Thank you!

**Comment by Kay0002** [comment]
You were right!! The iHeartRadio update was the issue. The last build of iHeartRadio that works with iDrive properly is v9.27.0_2021-01-12. I confirmed the AndriodAutoIdrive works fine (1.2.2-359-f65cd5e Feb 7, 2021 9:00:06 PM). 

Below are images of the iHeartRadio controls that I have and it automatically launches from.
![Uploading 20210218_100855.jpg…]()
![Uploading 20210218_102738.jpg…]()

![Uploading 20210218_102800.jpg…]()
![Uploading 20210218_102820.jpg…]()
![Uploading 20210218_102844.jpg…]()

**Comment by Kay0002** [comment]
Hi @hufman, interestingly the official iHeartRadio app disappeared once again. I confirmed my androidautoidrive, iHeartRadio, and connecteddrive apps are still the same version (nothing updated). Any thoughts as to why this happened again?

**Comment by hufman** [comment]
I don't have much insight into iHeartRadio. If Connected and AndroidAutoIdrive are running in the car but iHeartRadio is missing, did you plug in your phone before the Bluetooth Apps connection connected? That's the only thing I could think of that would cause that situation

**Comment by Kay0002** [comment]
No, I use Bluetooth. I don't use wired connection, except in the rare instances when I have to charge my phone.
