### ISSUE TITLE
Spotify Web API authorisation too often

### ISSUE THREAD

**Issue by Sven31415** [hufman/AndroidAutoIdrive#226]
Small problem: Spotify Web API has to be authorised nearly every day. Can this be fixed?
You can trigger this when going to the "music tab" and then make the app actualise the apps that are available.
I'm aware of probably needing to authorise Spotify again with every update, but it happens two to three times a day so there must be another issue too.
Best wishes,
Sven

**Comment by hufman** [comment]
Indeed! We're try to figure out what's going wrong.

**Comment by hufman** [comment]
We merged in a fix 2 weeks ago, and it seems to be working better, does it seem to be resolved for you too?

**Comment by Sven31415** [comment]
Sorry for the late answer; have been busy and also didn't manage to drive a lot with my car.
But yes I also noticed it became better. I don't get asked for authentication anymore, so you fixed it!
Thank you so much for your great work

**Comment by hufman** [comment]
Excellent! I'll close this out then.
