### ISSUE TITLE
Automatic Volume Setting

### ISSUE THREAD

**Issue by daniel1v** [hufman/AndroidAutoIdrive#234]
In the past days it happened to me several times, that the phone volume was at 0% and I had to increase it manually, to hear my music.

Maybe there could be an automatic volume increasement feature to 100%, when connection to the car is established?

If there is already such a feature, it seems like it does not work correctly sometimes.

**Comment by hufman** [comment]
Indeed! This was previously suggested in #133 and implemented in def7548 in November. Are you running the last release (1.2.2 from August)? This should be present in more recent builds, I sincerely apologize for the delay in finishing the next release.

**Comment by daniel1v** [comment]
> Indeed! This was previously suggested in #133 and implemented in [def7548](https://github.com/hufman/AndroidAutoIdrive/commit/def754850bde5382605506da75441c38cdcc1507) in November. Are you running the last release (1.2.2 from August)? This should be present in more recent builds, I sincerely apologize for the delay in finishing the next release.

Thank you for the fast reply. 

There is absolutely no need to apologyze, you are doing  very great work. 

Sorry, I forgot to mention, that I am always using the most recent nightly build, so it should work. I never had to worry about the phone volume before, so I think it used to work before. It only happened to me multiple times in the last days, but never before.

I will have an eye on it.

**Comment by daniel1v** [comment]
I think this issue can be closed. Today I had a similar problem with my Headset, so I think another App or the OS is the cause and it is not related to AndroidAutoIdrive. Sorry for the false alarm.
