### ISSUE TITLE
Black Notifications

### ISSUE THREAD

**Issue by Cisco79** [hufman/AndroidAutoIdrive#247]
Notifications now are all black-screen 
![WhatsApp Image 2021-04-12 at 16 01 40](https://user-images.githubusercontent.com/82391120/114407899-2ce64980-9ba9-11eb-9972-aec14d02808a.jpeg)

I use lastest relase of Bmw Connected and MyBmw in ID6
AndroidAutoIdrive build1.2.2-406-aba3910 8 Apr 2021

Before upgrade BmwConnected Notifications in Bmw ID were ok

P.S. thanks for your great work

**Comment by DominikS66** [comment]
Agree, same here
Id6, german language
![20210412_123213](https://user-images.githubusercontent.com/81849700/114419215-881d3980-9bb3-11eb-8bef-ddcb40352670.jpg)

**Comment by hufman** [comment]
Which screen is this? Is it the unlabelled book icon, or the car's built-in Notification Center?
Are you able to see if this change happened at a specific version, or if there's a previous version that worked properly, or is it based on the version of BMWConnected/MyBMW you are running? You should be able to access old AAI versions by clicking the green checkmarks in the [Git History](https://github.com/hufman/AndroidAutoIdrive/commits/master) and going to the Details, and then downloading the Artifacts from the top right.

**Comment by hufman** [comment]
Ah I just experienced it too! This is the popup screen, which is a special widget from BMW Connected. I wonder why the car stopped showing the widget at a certain time after removing BMW Connected from the phone!

**Comment by hufman** [comment]
Ok the latest build is updated with the fix 😅

**Comment by LACNR** [comment]
@hufman 

It worka fine for me but haven't updated to a newer version these days and have Connected isntalled, just for my notice was it related because you guys had BMW Connected uninstalled?

**Comment by hufman** [comment]
Yes the problem was that the code had a typo in the widgetsdb.zip filename and so it wasn't actually sending the widget for the ID5 Popup to the car. For some reason, the popup was able to use the widgetsdb.zip from the BMW Connected app that was running in the car, and was able to keep using it for a few days after uninstalling that app, at which point a cache expired and the widget stopped working.
While still running BMW Connected, or by updating to the latest AAI version, this bug should not appear.

**Comment by LACNR** [comment]
I see, thank you for explaining it to me and great you were able to track down what caused it for you guys 🙂 really interesting that it could still use it but for sure will update.
