### ISSUE TITLE
Missing text in id6 Connected Drive menu

### ISSUE THREAD

**Issue by DominikS66** [hufman/AndroidAutoIdrive#248]
Hello, there are menu entries without text in Connected drive menu. F20, iD6, german language, Aaid v1.2.2-406
![20210411_175627](https://user-images.githubusercontent.com/81849700/114419750-0083fa80-9bb4-11eb-9312-b412c6c5422b.jpg)
Or is this intended ?

**Comment by hufman** [comment]
Good morning! Yes this is intended, and a limitation of the unofficial app access.
The main Entry Button for each app that you see here in this app list has an icon and a label that is cryptographically tied to the certificate that was used to log in. This means the icon and label can't be changed, and so I instead opt to not send the text pack at all.
You'll notice similarly that I opted to not even send the icon pack for the Readout app. I needed to send it for the Notification Center support app, to be able to show the statusbar icon.

In ID5+, the car allows for greater interactivity through the placeholder icon api that I mainly use for the music app list (ID4 sometimes doesn't let me open windows after clicking the placeholder icon). I can use this functionality to add launchers elsewhere in the system, for example the Notifications entry in the Communications screen. I plan on adding a similar Map icon, when I figure out where I want to put it!
