### ISSUE TITLE
Spotify lädt sehr langsam

### ISSUE THREAD

**Issue by chrism2c** [hufman/AndroidAutoIdrive#256]
Spotify lädt sehr langsam. Wele version läuft am besten?

**Comment by chrism2c** [comment]
![Uploading 20210421_211117.jpg…]()

**Comment by chrism2c** [comment]
![20210421_211117](https://user-images.githubusercontent.com/82974537/115612036-1c417c00-a2eb-11eb-9de6-030de2f75622.jpg)

**Comment by chrism2c** [comment]
![Uploading 20210421_211216.jpg…]()

**Comment by hufman** [comment]
Hello! Can you tell me some more information about your setup? Has the connection worked before, but then shows this weird state after a reconnect (similar to this bug #254)?
If you open the phone app and tap the Spotify icon, does the player screen show any error messages or anything?
I suspect you are running the release from August (based on the Audioplayer app layout). The [latest build](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/androidautoidrive-latest-master-nomap-sentry-release.apk) might provide more debugging information, and also might fix the connection problem.

**Comment by chrism2c** [comment]
Hello. i think i found the problem. I'm using the version 2.2.2 from august 2020. i have now downloaded the new version.  Does it work with all spotify versions?  and thanks for the great program!!! I love it

**Comment by hufman** [comment]
I'm glad you figured it out, and thank you for the compliments!
The app should be compatible with all Spotify versions, with slightly different behavior depending on the specific version. For example, it can additionally talk the native MediaBrowser protocol with the super old 8.4.96 version, and AAI will log in to the car as the Spotify app to provide global coverart if Spotify >8.5.66 is installed. However, the Spotify Control API and Web API functionality should be compatible across all (uncracked) versions of Spotify within the last few years.
