### ISSUE TITLE
Antenne Bayern channel coverart is missing

### ISSUE THREAD

**Issue by TobifromGermany** [hufman/AndroidAutoIdrive#264]
Hallo, danke für die tolle Android Auto Drive App. Sie läuft perfekt mit der neusten Version.
Ich habe ein ID6 und MyBMW App.
Alexa Sprachsteuerung wird auch unterstützt. 
Spotify läuft ebenfalls problemlos. 
Können Sie für die Antenne Bayern App das Symbol /Icon hinzufügen?? Hier wird in der Kachel Media im ID6 nur die Schallplatte angezeigt. 

Ich hoffe die Android Auto Drive App wird bald im Plsystore verfügbar sein und ich wäre auch gerne bereit für diese tolle App etwas zu bezahlen!!

**Comment by hufman** [comment]
Good morning! Thank you for the kind words.
I installed Antenna Bayern and it looks like it's pretty well supported. It should add the app right to the car. Can you explain what is missing? Do you refer to the channel banner from Antenna Bayern not showing up as cover art?

**Comment by TobifromGermany** [comment]
Hello, yes, the Antenne Bayern app runs great and without problems in the car and is displayed immediately. All other channels in the app, such as Antenna Top 40, are also immediately displayed under favorites. Just perfect!!
Exactly, I'm referring to the Antenne Bayern channel banner, which unfortunately is not displayed as a cover. That would be great if it worked.
I have sent examples in the attachment.

Otherwise your AndroidAutoDrive app is really great !! I have your app running with the current version and with the MyBMW app and an ID6L. Even if the car is parked for a short time, everything is connected again immediately after the start.

Greetings from Franconia in Germany

Tobias
![Screenshot_20210427-180949_Antenne Bayern](https://user-images.githubusercontent.com/83277764/116276772-1fbe8280-a785-11eb-8ce2-b9b1c68b000d.jpg)
![Screenshot_20210427-180942_Antenne Bayern](https://user-images.githubusercontent.com/83277764/116276778-21884600-a785-11eb-91ac-334dbf8b421d.jpg)
![Screenshot_20210427-180928_Antenne Bayern](https://user-images.githubusercontent.com/83277764/116276780-2220dc80-a785-11eb-85ef-18d08752f732.jpg)

**Comment by hufman** [comment]
Cool, thank you for those pics. I'll take a look and see what's going on.

**Comment by TobifromGermany** [comment]
Thank you, perfect 👍

**Comment by LACNR** [comment]
@hufman Might this be related #251 as he said the cover is missing in the media widget (main menu?)

**Comment by hufman** [comment]
That may also be true, and @TobifromGermany please clarify if you see the cover art within the car app itself, but I observed that even the PhoneUI player didn't show any coverart so I suspect it's something deeper.

**Comment by LACNR** [comment]
Maybe the app doesn't share metadata of its channel icons, what about the song covers when a song is played with cover Art does it Show up in your widget (Kachel) in the iDrive @TobifromGermany

**Comment by TobifromGermany** [comment]
The app may not share metadata of its channel icons. What about the song covers when playing a song with cover art? It will be displayed in your widget (tile) in the iDrive @TobifromGermany

No, no widget (tile) whatsoever is displayed when a song with cover art is played.
However, you can see a small cover of the Antenne Bayern app in MyBMW, for example.

For comparison, the covers of the various stations are displayed in the Radio Fm app. The covers of the songs are also displayed under Spotify.

**Comment by hufman** [comment]
Happy good morning! I fixed this bug, and also sorted Antenne Bayern into the Radio section of the car.
Turns out I haven't implemented CoverartUri loading in the Phone UI player, so the Phone UI still won't show the coverart, but I verified in the car that it is properly loading the coverart.

**Comment by TobifromGermany** [comment]
Yes this is really a happy good morning !!

The Antenne Bayern is now running perfectly. The covers are displayed as well as those of the current title.
Thank you very much for this awesome app. I'm excited!!

**Comment by TobifromGermany** [comment]
The Rock Antenne App also runs very well on AAiD ;)

**Comment by hufman** [comment]
Yay! I'm glad to hear it :)
