### ISSUE TITLE
Playlist Soundcloud AmazonMusic 

### ISSUE THREAD

**Issue by Shokwaves84** [hufman/AndroidAutoIdrive#270]
Hello

many thanks for the great app.

I have the problem that I can't select a playlist/ favorites   on Soundcloud and AmazonMusic.

it is only displayed "Search empty". 

And

i can't see the cover in the little menu (Spotify,Soundcloud,AmazonPrimeMusic)

(Homescreen.)

BMW G31 8/2018

Sorry for my english. I hope you know what I want to tell you anyway

many thanks

**Comment by hufman** [comment]
Welcome, and I'm happy you like it! I am also a fan of Soundcloud.
However, AAI can only control the music apps through the control they grant. [Amazon Music](https://apkpure.com/amazon-music-stream-and-discover-songs-podcasts/com.amazon.mp3/download/517080510-APK?from=versions%2Fversion) doesn't allow AAI to connect to start or control it at all, and the method of controlling running apps doesn't offer a way to browse. [Soundcloud](https://apkpure.com/sound-cloud-android/com.soundcloud.android/download/73060-APK?from=versions%2Fversion) just simply doesn't implement browsing at all, returning an empty library to every app (include Android Auto itself).

Are you seeing the app show up as Audioplayer? It won't be able to set the global coverart if it's running in that mode. You may need to upgrade AAI to a [nightly build](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/androidautoidrive-latest-master-nomap-sentry-release.apk) and make sure your Spotify is up-to-date.

**Comment by Shokwaves84** [comment]
Hey..

Many thanks for your support. an update of your app was the solution for the cover 

I love it.

you should take money for this app, mate.

Sometimes the Idrive Bluetooth Connection Apps lost
