### ISSUE TITLE
Deezer Playlist view not working

### ISSUE THREAD

**Issue by Tuerkay** [hufman/AndroidAutoIdrive#274]
A friend of mine saw AAI working with Spotify in my ID6 car and asked if i can help her get it working in her car.
Her BMW has an NBT system, so i installed BMW connected classic since BMW Connected won´t connect to the car properly.
Build the latest nightly and installed it. In contrast to me, she uses Deezer instead of Spotify.
Her Samsung A52 connected to the car, AAI started and Deezer showed up in iDrive. Cover and title are showing and songs are controllable. Sadly the playlist button is grayed out and we can´t search for songs through iDrive.
So i´d like to know if Deezer is even fully supported by AAI? Do i need to change something in the build or is the song library just not accessible through iDrive/AAI?

**Comment by berseker** [comment]
afaik Deezer unfortunately does not support advanced features of Android Auto that can be used by AAI

**Comment by hufman** [comment]
I took a look inside the [Deezer app](https://androidapksfree.com/deezer/deezer-android-app/download-old/deezer-6-2-26-23-6210902-apk/), and it seems to block access to control it without the Notification Access method. Being able to browse the app requires full access, however.
The Now Playing feature would work, it would work with Notification Access, but it sounds like Deezer doesn't implement it. You can run the official Android Auto to confirm if Deezer provides a playlist to it. (Some apps can do some naughty tricks, like switching to a special mode that enables certain functionality only if a valid client app is connected, but that can't be worked around either.)
I'm sorry, but there isn't any way around it without Deezer allowing support on their side. Please try to reach out to their customer support to see if they can add it to a feature wishlist!
