### ISSUE TITLE
Start Simple Radio instead of Spotify

### ISSUE THREAD

**Issue by unlive74** [hufman/AndroidAutoIdrive#275]
I use the Simple radio and Spotify apps and if I try to start Spotify on my car, but the application is not active, it doesn't start, instead the simple radio application starts and it works until I launch Spotify on my phone. And after that Spotify starts working in the car. It is very strange..
![20210506_125854](https://user-images.githubusercontent.com/75434533/118078388-87084380-b3cf-11eb-88e9-ebe36abb9073.jpg)

**Comment by hufman** [comment]
Ah, I think you are encountering a special behavior of the Spotify app icon. When you push the Media shortcut button next to the IDrive controller, the car clicks that Spotify icon to bring up the app display. Of course, you don't want the music to switch to Spotify every time you click that button, so AAI watches what screen your car is showing, and will only switch to Spotify if you stay on the music app list screen for more than a few seconds before clicking Spotify. Next time you're in the car, allow this app list screen to show for a few seconds before clicking Spotify. I might need to tune the thresholds some more.
Once in the app, there is a toolbar icon on the top left that will bring you to a custom-built app list, and this list will always switch to the app you click.

Does this behavior match what you are seeing?

**Comment by unlive74** [comment]
Yes, I think you are right. I'll watch, but I think it looks like it's described.

**Comment by unlive74** [comment]
@hufman when I turned off the car playing spotify.  at startup, anything is launched, but not spotify.  further shown in the video:

https://user-images.githubusercontent.com/75434533/120077326-5f99c200-c0c3-11eb-940a-442e791b24ce.mp4
