### ISSUE TITLE
Problems with Android 11? 

### ISSUE THREAD

**Issue by bastianp01** [hufman/AndroidAutoIdrive#281]
Hi. First of all thanks for your great job and this project.
Can I ask for help with my Android 11 Samsung Smartphone?
The problem is that suddenly the BMW connected App dies Not Show the little car icon in the Status Bar anymore. As a result the androidauto idrive App keeps saying "waiting for connection"
I tried two different smartphones with Android 11. Both with the same Problem. Bluetooth is activated and working. But the App is Not connecting anymore to the car via USB.
I installed the mybmw App. With this App i can get the little car icon in the Status Bar. Is it still correct that androidauto idrive does not work with mybmw app?
Do you have any idea why i got this Problem?
With my old samsung a3 2017 it is still working. 
Thanks for your help!

**Comment by Marc2480** [comment]
@bastianp01 Can only confirm that for me AAi 1.2.2-445, MyBMW 1.4.0 (7743) and latest Spotify work exceptionally well on my S20 with latest A11 (car is X3 with ID6). I would say 95% of the time all connects automatically and Spotify even picks up where it was left during previous drive (multiple stops & restarts etc). The 5% of the time I loose Spotify library access, then I simply restart the phone and all is good again ... maybe not much help for you but just wanted to point out at Android 11 is likely not a general issue ... thx!

**Comment by jezikk82** [comment]
Check battery savings settings.
In Android 11 (similarly in Xiaomi phones earlier) system is killing apps working in background after some time causing symptoms as you stated. 
In my wife's phone (S20 FE) after adding MyBMW&AAiD to "No battery saving mode" everything works fine.

**Comment by bastianp01** [comment]
Hi thanks for quick response!

I already tried to set the apps BMW and AAiD on any whitelist i could find ;) incl the battery saving mode. I checked all the FAQ and relevant issues on this site but i reached the point where I have no idea left.
The stange thing is, that the problem came up suddenly without any changes by myself. It worked like 80% very well and then after an update of my smartphone it stoped working. And on my old Samsung A3 it is still working.

I tried to find out what iDrive version my car has. It is a BMW 4 from 2014 NTB ID4. Is it to old to work with the MyBMW App? 

@Marc2480 thanks for your feedback. It never worked with the MyBMW App in my car. Only with the BMW connected App ... I use a Samsung Galaxy A40 ... not a high end smartphone ... is it possible that it will work better with S20 ?

**Comment by Marc2480** [comment]
@bastianp01 sorry, have only used AAi with my S20, no other phones to test ...

**Comment by bastianp01** [comment]
Wow thanks. With Connected 6.4 the AAiD App connects to the car again. For some reason Spotify and the other Apps like Calender still do not appear in the car but I had this problem before. Do you have any Idea what I am doing wrong? Bluetooth is on, Spotify plays music via bluetooth, all Battery saving modes are off, MyBMW is uninstalled and only the Connected 6.4 works with AAiD. Is my car from 2014 to old for a stable connection?
And my I ask another question? What is a nightly build? ;)

Thanks a lot for your help so far. I will just continue to connect the phone to the car and hope that it will start wokring again

**Comment by hufman** [comment]
I've seen it occasionally where the Connected app gets slightly confused about whether it should be running or not. The actual tunnel to the car stays up, and AAI finds it and uses it, even if Connected didn't try to start its apps. It usually comes back on its own, in my experience, though it does appear random.
I don't think it's due to the age of your car!

A nightly build is an automated build of a project that represents the version of the code each night, as opposed to the hand-picked stable release version. It's a slight misnomer, because the build process for AAI kicks off after every change and will update the latest build available automatically, but "nightly build" is a common term and close enough for usefulness.

**Comment by bastianp01** [comment]
Thanks for the Infos and your time. I just found out that Android makes automatik Updates for the connected App so I now have the same Problem again. I will uninstall it and install the older version again. Is there any way to deny auto Updates for Single Apps or is it the only way to Set all Auto Updates to off?

**Comment by hufman** [comment]
Of course! If you bring up the app in the Play Store, in the screen with the Uninstall or Open buttons, you should be able to click the three dots in the upper corner and disable the toggle named Enable Auto Update.
