### ISSUE TITLE
Connected App deactivated on 30.06.2021

### ISSUE THREAD

**Issue by MrFloutsch** [hufman/AndroidAutoIdrive#288]
Just got the notification on my connected app, that the service is going to be deactivated on 30.06.2021 and i should download the newer My BMW App.
What does this mean for AndroidAutoIdrive?

**Comment by bogdan-calapod** [comment]
Nothing much for now - the new MyBMW app supports the Connected Apps protocol, although it does have some issues (#244)

**Comment by LACNR** [comment]
If you have a BMW that doesn't support Bluetooth Apps and you need to connect your phone via USB to use Connected apps and AAiD, you will need to downgrade to the Connected 6.4 version of BMW Connected to continue using AAiD - although it is enough to have the Connected App installed your phone, there's no need to login into the old BMW Connected app. If you have subs to further BMW services it is recommended to also install MyBMW to be able using them.

Right now, MyBMW doesn't support Apps connection via USB connection, officially it doesn't support Apps at all but it is somehow enabled and functional in the MyBMW via Bluetooth for BMW's with the Bluetooth Apps option.

**Comment by MrFloutsch** [comment]
Thanks for the quick replies, that answers my question.
