### ISSUE TITLE
Read out new phone notifications

### ISSUE THREAD

**Issue by hufman** [hufman/AndroidAutoIdrive#29]
Now that the TTS api is [figured out](https://hufman.github.io/BMWConnectedAnalysis/speech/), there could be an option to read out new notifications as they come in, or perhaps read out the notification in the list view.

**Comment by jezikk82** [comment]
Hi, I wanted to test this future but I got an error message: "Function temporary unavailable".  Does it support only English or any TTS voice that is in phone/car ?
The second issue I saw was when I tried to read the notification on normal way, it said error as above and close the notification.  So with enabled read out option you are not able to read notifications in the traditional way.

**Comment by hufman** [comment]
Thank you for trying to test! The protocol doesn't allow for specifying the language, so it should just use what language you've set in the car.
I've seen that error happen if the car was already reading something out when I trigger another message, not sure what it would mean otherwise. I should add a check to make sure the car supports TTS before trying to use it though. If you don't mind, could you peek in your car's capabilities (for example, add a log statement [in here](https://github.com/hufman/AndroidAutoIdrive/blob/master/app/src/main/java/me/hufman/androidautoidrive/carapp/notifications/NotificationSettings.kt) or [here](https://github.com/hufman/AndroidAutoIdrive/blob/master/app/src/main/java/me/hufman/androidautoidrive/CarInformationDiscovery.kt#L35)) to see what your car's "tts" capability says?

I'm not sure about the second issue, the only time it should be closing out the notification and going to the main list is if the selected notification gets swiped away on the phone (specifically, any time the notification list changes and the selected notification is no longer in the list). I'll check to see if there's some faulty error handling somewhere!

Thank you again!

**Comment by hufman** [comment]
I pushed a change to check the car's "tts" support before trying to use it. The car view of the notification list should only show the Read Notification settings if the car supports it, can you tell me if those settings show up in the car?

**Comment by jezikk82** [comment]
I checked that in 2 cars. 
Result are as follow:
- F48 (ID5) with native English HMI and language that works and debug report TTS true.
- G30 (ID6) from 2017 with language set to Polish that don't work, with tts false. Checked with France lang as well but that didnt work. In Idrive menu I have voice communication up and running in that car. So my suspicion in that it works only with English? Can anybody else confirm that issue ???

After you added the check to the code I don't experienced the problem no 2 mentioned above.

**Comment by hufman** [comment]
I posted a request to the Gitter for more people to try it out and report if it works in their cars.
Thank you so much for sharing the tts value, and that my new check avoids that incorrect behavior. I hope we can figure it out!

**Comment by hufman** [comment]
Have you done any coding of your car? I found this setting which might be related, and is aktiv in my car: `HU_NBT > HMI 3000 > SYSTEM_TTS`

**Comment by jezikk82** [comment]
I had some coding done, let me check later that value.
