### ISSUE TITLE
Implement notification input

### ISSUE THREAD

**Issue by hufman** [hufman/AndroidAutoIdrive#3]
Some notifications have a Reply action with a text input. This input could use a short list of common replies (some notifications even provide a list of replies), and a more functional text input screen with word autocomplete (perhaps using slashes and dashes to quickly select words) could be implemented.

**Comment by hufman** [comment]
Idrive 5 and 6 can do voice input on the Input State, which makes this very compelling.

**Comment by bogdan-calapod** [comment]
Is this integrated ? From my experience it works quite well - maybe add a "canned response" feature ?

**Comment by hufman** [comment]
Indeed! I had left it open until I finished a list of other improvements which only exist in my head so far 🙈 

- ~word completion~ the car doesn't seem to like me editing the input, so I can't implement word completion
- Emoji suggestions
- A list of quick replies
