### ISSUE TITLE
Volume boost when streaming bluetooth audio 

### ISSUE THREAD

**Issue by jtangelder** [hufman/AndroidAutoIdrive#305]
I noticed that the audio streamed over bluetooth is notability softer than the other audio (radio, cd). If possible, it would be great to have an option to boost the volume a bit when streaming audio to the car.

**Comment by hufman** [comment]
Good morning! What is your phone's volume while connected to the car? As part of #133 , AAI will try to set the volume to max when the Bluetooth Music connection starts up.
Does your phone show the warning about not listening to headphones too loudly? I wonder if that is interfering somehow, and the phone is only allowing the app to set it to the max safe level?

**Comment by LACNR** [comment]
@jtangelder You have to max out your bluetooth volume when in car on your phone, this is independend from the AAiD app. Most phones have safety feature that on first connection the bluetooth volume will be on a safe to hear level and it will stay that way until you increase the volume on your phone yourself. You have to max it out to have full volume for the in-car bluetooth.

Yeah I think the warning/safety restricts an automated increasing. Eventually when listening with different gadgets, such as Bluetooth speakers, airpods the volume is usually decreased automatically and can be maxed out manually, so I assume when switching back to car it may happens that it keeps the previous volume level you used for your headphones which is usually below the warning level.

It happens once in awhile to me but usually once I had to manually max out the Bluetooth volume it stays that way at every connection, however I will test if it is related to that when using e.g. earpods on low level will stay on low level when back in car.

**Comment by jtangelder** [comment]
Phone's (Pixel 4XL) bluetooth volume is set to 100%, so it already is at max. No warnings whatsoever around max limit, I've seen those before, but not in this situation with the car connected. 

There are some apps available in the Play Store that can help you to add more gain (=more volume) to the output, I guess they're all making use of the LoudnessEnhancer API from Android? Greatest pitfall of these apps (those that I tested), is that you'll manually have to enable them. 

https://play.google.com/store/apps/details?id=sound.beautifier.bluetooth.music.more.bass.low.volume
https://developer.android.com/reference/android/media/audiofx/LoudnessEnhancer

**Comment by LACNR** [comment]
I don't have any problems with the volume sound, in general for all vehicles to have full audio feedback in your car you have to max out the bluetooth volume on your phone so you don't have to increase in-cars volume much (10-40% of 100%)

If your phones volume is at max, it must be a problem with your phone or the in-car equalizer has a low setting selected or some internal equalizer is interfering.

Make sure you have the latest update for your car: www.bmw.com/update

**Comment by jtangelder** [comment]
10%-40% is still significant, and kind of the amount that I'm talking about :-) 
My BMW F48 is running the latest software.

**Comment by LACNR** [comment]
I'm sorry but if 10-40% in-car volume level is significant to you when there's no solution, that is depending on your preference the usual level one has to increase the in-car volume to have a solid loud but not too loud audio output.

Beware Bluetooth audio is usually quieter by default than streaming via hardware (CD, USB, HD, Radio...) 

It also depends on your sound system, the standard sound system is eventually not enough for you if you have it as of course the HiFi System and the top tier Harman/Kardon system.

You should consider checking out there's also a Speed volume trigger in the cars audio settings, increase it so the volume will dynamically increase depending on your speed.

**Comment by hufman** [comment]
Thank you for the links to investigate! The Audio Enhancer API seems to only support attaching to a MediaPlayer object that is owned by the app itself, instead of controlling the system-wide mix. I wonder how those equalizer apps do it.

**Comment by masteralarm** [comment]
I got a problem that might be linked to the volume boost feature in #133: After leaving the car, the system audio (via phone speakers) is (often) set to max. 
Might this be because of AAI? Is there an advanced option to deactivate this behavior?

**Comment by hufman** [comment]
AAI tries very hard to make sure that Bluetooth Music is connected before [adjusting the volume](https://github.com/hufman/AndroidAutoIdrive/blob/e53227b7c3a82a87791a53f5d9511e7e9de8540d/app/src/main/java/me/hufman/androidautoidrive/MusicService.kt#L91), specifically to prevent such a problem. I remember BMW/Mini Connected Classic did this all the time for me, so I wanted to avoid it.
To narrow down if it's a bug in AAI or not, you should try connecting to the car without AAI installed and see if it still happens. I would rather fix a bug and keep doing the best UX automatically, as opposed to adding another option.

**Comment by masteralarm** [comment]
Hey, I just tested it again:
Without AAI installed, the phone volume stayed the same after listening over BT and then leaving the car.
Reinstalled AAI and tested it again (with using the AAI music app in the car), phone volume was at max after leaving the car.

Perhaps important information:
Using the Connected App 6.4 for the connection to the car.
When I normally arrive at a destination, I switch off the engine, stop the playback (pushing the volume knob) and then disconnect the phone from USB. Might this order have something to do with this?

**Comment by masteralarm** [comment]
So I just spend half an hour in the car turning the ignition on and off repeatedly, and I think I can now reproduce it:

Audio is playing via Bluetooth and phone is connected via USB.

- unplug USB, then stop ignition (head unit shuts down, Bluetooth gets disconnected): **phone volume stays normal**

- Stop ignition (head unit shuts down, Bluetooth gets disconnected, AAI reports still connected), then unplug USB: **phone volume now at max**

Does this help to find a solution in AAI's logic, or is the only solution to follow the correct procedure when disconnecting (first unplug USB, then BT off)?

**Comment by hufman** [comment]
I suspect the Bluetooth Status listener (to watch for the Bluetooth connection after the Music app starts up) is mishandling the update event about the disconnection. I just pushed up a change to unsubscribe from those update events after it sets the maximum volume the first time, which should improve your disconnection experience.

**Comment by hufman** [comment]
@masteralarm Did that recent change help?

@jtangelder I forgot to ask: Does your phone allow you to increase the volume, or is the app properly setting the media volume to the maximum level automatically? And if you have ID5, is there a volume difference between the car's native Bluetooth media source and the app's media sources? If your car's Bluetooth media is similarly quiet, I'd be more comfortable recommending an external app to tweak your audio levels, instead of trying to come up with a solution that tries to work for the general case.

**Comment by masteralarm** [comment]
Sorry, I forgot to answer.

In the meantime I discovered that it was indeed the "BMW Connected" App that was also setting the volume and together with AAI it was difficult to understand what was happening.
As I am now switched to the new "My BMW" app, it seems that the issue is no longer a problem for me.

Fun fact about the old "BMW Connected" app behavior: It also was setting the volume to the max, as soon as it was connected via USB. When unplugging, it automatically resets the volume (it seems to store the inital value). Problem was that it did not check which volume it was setting, i.e. this could easily happen:

1. Enter car and plugin the USB -> BMW app sets volume to max (that would be the phone speaker volume, as Bluetooth is not yet connected)
2. Drive and listen over Bluetooth
3. Stop and unplug (Bluetooth still connected, as iDrive is still running)
4. BMW app resets volume to inital value (but this this the Bluetooth volume, while the normal media volume stays at max)

Clearly not something you would want ;)

**Comment by hufman** [comment]
Ah ha ha that's awesome, great debugging!
