### ISSUE TITLE
Heads Up Display

### ISSUE THREAD

**Issue by ahershey21** [hufman/AndroidAutoIdrive#306]
I have a 2019 530e with Heads Up Display. AndroidAutoIdrive works great with multiple sources showing up. 

One thing that I have noticed is that on the Heads Up Display, all the sources that the app makes active only show up as Spotify, so cannot cycle through the Mode switch. Of note, when in the Spotify Mode with AAI, I can move through songs on the HUD, so that all works great.

Not sure if this is fixable, as it may be that the app is utilizing Spotify conduit, but thought I would ask.

**Comment by hufman** [comment]
I'm so happy you like it! You are exactly correct: The only real music app (with an RHMI menu) is Spotify (or the legacy Audioplayer), and all the rest are just placeholder icons in the menu. Unfortunately, the RHMI app is dependent on BMW-signed data files and can't be modified to show a different icon, while only the RHMI music apps show up in the sources quick menu or included in the Mode button cycle. This is also why only the Spotify app gets a checkmark in the Media menu.
Expanding the functionality would need BMW's cooperation to provide RHMI resources that allow different icon packs. If that happens, I'd love to incorporate them for an even tighter integration! Until then, this is as much as I can do.

**Comment by ahershey21** [comment]
Thank you. Here is to you enjoying your "cup of coffee" :)
