### ISSUE TITLE
Android Studio build issue

### ISSUE THREAD

**Issue by ericgla** [hufman/AndroidAutoIdrive#31]
After loading the project in a fresh install of Android Studio (Windows), I get the following error:

3:06 PM	Unsupported Modules Detected: Compilation is not supported for following modules: app, IDriveConnectKitAndroid, AndroidAutoIdrive, IDriveConnectKit. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project.

Is there any additional setup that needs to be done in order to build?

**Comment by hufman** [comment]
Thanks for testing it out!
I think I may have left some extraneous IDEA files in the repo which may be confusing the IDE. I was not able to reproduce this problem, but I think the incorrect files would definitely not help.
I pushed up a change which deletes these extra files, and also updates to the latest IDE and Gradle versions. I was able to do a fresh clone and build the project, so please test it out on your end!

**Comment by ericgla** [comment]
That fixed it, and I'm able to build now, thanks!  FYI - I am using the app with an NBT Evo head unit and is working well so far.  I'm looking forward to trying out the maps feature.

**Comment by hufman** [comment]
Glad to hear! Let me know if you have any other questions or suggestions!
