### ISSUE TITLE
A question for the first installation 

### ISSUE THREAD

**Issue by Roxo69** [hufman/AndroidAutoIdrive#313]
Good evening everyone and thanks a lot to the developers of this fantastic app.
I have a question about the first installation,to make the app work properly in version 1.3rc1, you need to download all 6 download or just download one of androidautoidrive-1.3rc1-nomap-sentry-release.apk(11.7 Mb) or androidautoidrive-1.3rc1-nomap-nonalytics-apk(11.5 Mb)?
In other words the app works the same if I don't download the files androidautoidrive-1.3rc1-nomap-sentry-release.apk.sha(92Bytes),androidautoidrive-1.3rc1-nomap-nonalytics-release.apk.sha1(96Bytes),Source code(zip) and Source code(tar.gz)?

**Comment by hufman** [comment]
Good evening, and welcome!
You only need to download and install one of the APK files. The .sha1 file is a checksum of the matching APK file, and the source code files are only if you want to compile a specific version yourself without obtaining the source through git. The only file you need to download is either of the APK files.

**Comment by Roxo69** [comment]
Thanks again and congratulations for the skill !😉
