### ISSUE TITLE
Spotify requires authorization on every start

### ISSUE THREAD

**Issue by wdata68** [hufman/AndroidAutoIdrive#317]
Thank you for your wonderful piece of software!
Since some weeks I have strange behavior, every time the program started in the car I have notification about required authorization in the Spotify both on the headunit and on the phone. When I click it on the phone, the normal Spotify "Accept application" screen appears, where I can accept application till next time.
About a week ago I installed the latest nightly build, but it didn't help. Then cleared out all cache and data, and the problem disappeared. But it has come back when I restarted the phone.
Phone: Samsung S20 (SM-G980F/DS), Android 11
AndroidAutoIdrive version: 1.2.2-475-9f844f5
Spotify: 8.6.32.925

I am ready to provide any additional symptoms.

**Comment by wdata68** [comment]
Short clarification: it appears it's not on every start, but once a day.

**Comment by hufman** [comment]
Hmmm I know earlier versions had a similar problem, but that should have been resolved a few months ago. The Notification comes through the code that initializes the Web API access, which is primarily used for searching, so the actual music playback functionality should still work fine.
Thank you for the report! I'll keep my eye out to try to figure out how it could happen.

**Comment by wdata68** [comment]
>  I'll keep my eye out to try to figure out how it could happen.

I believe I can close it for now. The problem has disappeared in the same sudden way it appeared. It could probably be related to the Spotify version and gone after some update. Sorry I've disturbed you.
