### ISSUE TITLE
Automatischer Stopp der Musik App am Smartphone nach Zündung aus

### ISSUE THREAD

**Issue by TobifromGermany** [hufman/AndroidAutoIdrive#318]
Hallo,
gibt es eine Möglichkeit oder ist es nur eine Einstellungssache das die gerade laufende Musik App über AAID am Smartphone, nachdem man die Zündung ausschalten, auch gestoppt wird!?

**Comment by hufman** [comment]
Good afternoon! There in fact used to be such a feature, but my ID4 car had a flaky USB cable and the auto-stop would kill the Bluetooth music if the USB disconnected briefly :) Instead I've been relying on the autostop functionality of the Bluetooth disconnection event.
With the improved support for audio context, I can add this back in easily enough.

**Comment by TobifromGermany** [comment]
Das wäre ja super wenn es diese Funktion wieder gibt :) aber keinen Stress, die App läuft ja auch so richtig gut!!!
