### ISSUE TITLE
Spotify songs number limited on dashboard

### ISSUE THREAD

**Issue by donsaimon** [hufman/AndroidAutoIdrive#328]
I have a Spotify playlist of 126 songs.
On the dashboard, I can only see a little part of them (sometime 15 or 16 songs, sometime about 20-30) and I can browse among them (and among them only) via steering wheel rotary control. 
The only way to see all the songs belonging to my playlist is to browse them using iDrive control wheel and looking at the multimedia display.
Moreover, if I select "next song", I can skip 6 songs only: after that the voice "next song" is no more present on the dashboard and is greyed (not selectable) on the multimedia display. Nevertheless I can still browse songs.

**Comment by hufman** [comment]
Indeed, the steering wheel playlist [is limited](https://github.com/hufman/AndroidAutoIdrive/blob/c87b4875ca2af173425624768b5d64514516dd78/app/src/main/java/me/hufman/androidautoidrive/carapp/music/GlobalMetadata.kt#L99) to 15 songs previous and 25 songs forward from the current position. I feel it is unergonomic to try to navigate larger distances on the tiny dashboard screen, and sending a sublist of the playlist to the display allows it to update faster. Scrolling through a large playlist is definitely faster using the idrive controller, and note that the Now Playing button can be saved as a dashboard shortcut button.
The back/next enabled status depends on the commands that the underlying Music app provides: If AAI shows the Next option as greyed out, then Spotify has told AAI (and would similarly tell Android Auto and the lock screen and any other clients) that the Next command is not available.

This is working as intended, unless you'd like to see a different behavior?

**Comment by donsaimon** [comment]
Thanks a lot for the explanation. I did not know that the one I described was the expected behavior.
Effectively it would be great if it was possible to make more skips before the "next song" command became grey....

**Comment by hufman** [comment]
AAI can't change much in that regard, it is only relaying the command availability from the app itself. Does it stay enabled if you enable Shuffle or Repeat options? I haven't seen it grey out in the playlists I've tried and so I don't know more suggestions.

**Comment by donsaimon** [comment]
Even if I select repeat option, after 6 skips the "next song" button becomes grey, it is disabled... Maybe because I do not have premium?

**Comment by hufman** [comment]
Yeah it looks like free accounts are limited except for certain special playlists: https://community.spotify.com/t5/iOS-iPhone-iPad/skip-limit/m-p/4877209#M118656

**Comment by donsaimon** [comment]
Ok understood.
One thing I have noticed about Spotify is that sometimes the "now playing" button on the left menu is greyed, so that it is not possible to browse the songs.

**Comment by hufman** [comment]
It seems that some playlist types aren't navigable, such as Radio Mixes and so on.

**Comment by donsaimon** [comment]
I am using a playlist I made, not one made by Spotify.

**Comment by donsaimon** [comment]
Please remove the limit of maximum songs in the dashboard, as if I use the "next song" command I can only listen at the songs displayed on the dashboard, that are lot less than the songs I have in my playlist...
My playlist has 126 songs, but I can only see from 20 to 40 (I don't know why this number varies every time), and with the "next song" command it cycles among that 20-40 songs only...

**Comment by hufman** [comment]
May I ask what functionality you prefer in the dashboard compared to using the Now Playing view in the idrive screen? The dashboard playlist is meant for quick selections while the idrive screen can be used to view the entire playlist.
The Next command merely [pushes the Next button](https://github.com/hufman/AndroidAutoIdrive/blob/545f14fc9211ad964e9b8a8192aa1e275fdf1128/app/src/main/java/me/hufman/androidautoidrive/carapp/music/GlobalMetadata.kt#L144) on the music app, the exact same as pushing the Next button in the app's notification or the lock screen or a Bluetooth headset, and does not change behavior based on the size of the dashboard playlist, or even whether a playlist is loaded at all.

**Comment by donsaimon** [comment]
I prefer using the dashboard list as it is more immediate and easy when I am driving. I simply scroll down the rotary control I have on the steering wheel and push: in this simple way I can pass to another song (when the "next song" command is greyed) with less controls. With iDrive wheel I have to make more operations to arrive to the list (that, at least in my car, is quite slow to load)...
As I told, I have noticed that the "next song" command seems to chose the song among the little subset displayed in the dashboard and not among all the songs of the playlist...

**Comment by hufman** [comment]
Yes, as you can see from the source code, the number of songs visible depends on the position of the current song in the list: It only shows up to 15 songs behind and 25 songs ahead of the current position. If the current song is near the end, fewer entries will be shown.
As the code also shows, the Skip Next entry has no logic to constrain what songs it picks. It is the exact same Next command that is used by the hardware back/next buttons next to the bookmark buttons and the same Next command used by the main interface. Changing the count of displayed songs, or whether any playlist is displayed at all, will not affect this.
I can not remove the limit of the count of songs displayed in the dashboard, because the amount of data transferred will negatively impact performance and cause the list to update slowly, and is much less ergonomic than the full-size view. You are welcome to compile it yourself and remove the limit for yourself, of course.

**Comment by donsaimon** [comment]
Ok Walter, thanks for the explanation. Unfortunately I am not able to compile the code by myself.... So... The limit will remain... 😅
