### ISSUE TITLE
Something broke in recent builds and bt audio disappeared.

### ISSUE THREAD

**Issue by unlive74** [hufman/AndroidAutoIdrive#330]
Something broke in recent builds and bt audio disappeared. If I switched to radio, then I have no chance to listen to Spotify. [Here](https://photos.app.goo.gl/eiYDxdjaCNev26cN8)

ps: c87b487 works well.

**Comment by hufman** [comment]
I don't think the picture came through.

**Comment by unlive74** [comment]
> I don't think the picture came through. Are you saying that the Bluetooth audio source from the car disappeared entirely?

 [fixed link](https://photos.app.goo.gl/eiYDxdjaCNev26cN8)

**Comment by hufman** [comment]
Do you have "Always appear as Spotify" enabled? Its acting like it didn't get audio context, are you plugged in through USB at this time?

**Comment by hufman** [comment]
Good news, I was able to reproduce this and will look into it. Thank you for the report!

**Comment by unlive74** [comment]
@hufman it seems to me that the latest builds are worse connected to the car.  3 days ago this worked almost always (may be 95%), but now only 50%.  Connection occurs if you run AAID.
