### ISSUE TITLE
Spotify account was blocked

### ISSUE THREAD

**Issue by andreasbaum123** [hufman/AndroidAutoIdrive#342]
Today my Spotify account was blocked for violating the terms of use. Could this be due to using AutoAndroidIdrive? Does this program violate the Terms of Use? I don't have any other software running that accesses Spotify.

**Comment by hufman** [comment]
That would certainly be surprising! I haven't heard of this happening to anyone else. AndroidAutoIdrive uses the official Spotify SDK to control Spotify, and does not try to workaround or access Spotify's data through any unofficial means, and any misuse in that regard should come down on AAI itself, not on any users. The SDK blocks attempts to use any modded Spotify clients, and AAI specifically does not try to work around this restriction.
Did they provide any further information for what specific Terms of Use were violated?

**Comment by andreasbaum123** [comment]
I checked it. I use Shazam with Spotify, Alexa with Spotify and AndroidAutoIdrive with Spotify. No other Apps. Spotify didn't answer why I violated the Terms of Use.

**Comment by andreasbaum123** [comment]
I get my account back. But no reason why I violated the Terms of Use.

**Comment by andreasbaum123** [comment]
I now know the reason and it is NOT AndroidAutoIdrive! 😁

**Comment by hufman** [comment]
Hooray! But now you've piqued my interest, what was it?

**Comment by andreasbaum123** [comment]
3 month ago I test for only 1 day tools with using the high speed download feature to download songs for my watch in mp3. That was it.
