### ISSUE TITLE
"Ability to browse Spotify library" doesn't work

### ISSUE THREAD

**Issue by unlive74** [hufman/AndroidAutoIdrive#343]
Hi Walter!

Maybe there is a way to fix the Spotify library browsing ability? Now it works like this:

https://user-images.githubusercontent.com/75434533/125101282-7df7d200-e0f3-11eb-9150-120b75dd20b0.mp4

log: [logcat_07-09-2021_17-47-36.txt](https://github.com/hufman/AndroidAutoIdrive/files/6792422/logcat_07-09-2021_17-47-36.txt)

**Comment by hufman** [comment]
I'm sorry to hear this isn't working for you! It's one of the best features of the app.
Is your Spotify app running, and is it allowed to run in the background? Does it help if you kill it and start it again? That error message only tells me that the Spotify SDK never received a response from the Spotify App for some reason.

**Comment by unlive74** [comment]
it worked after reboot, thank you
