### ISSUE TITLE
[Future req] BMWApps data supply, eg. Weather

### ISSUE THREAD

**Issue by jezikk82** [hufman/AndroidAutoIdrive#35]
HI,

could you try to add connectivity between bmw apps (e.g. weather) and online services. I heard  that somebody from Russia developed such an app that restore online connectivity through Bluetooth teetering in case your subscription is over or broken telematic box (sim card problems). 
Many apps are still able to get content from ConnectedDrive servers without problems, except the subscriptions (e.g. RTTI) and auth messages.

Other approach could be for example to get weather use different weather source and just give proper xml file to head unit to present it in many places and give alerts (e.g. storm, heave rain, snow, ice on road).

**Comment by ericgla** [comment]
Internet connectivity via Bluetooth can be enabled via coding.  You'll need to make the following changes to your VO:

Add 609, 6AK, 6NS, 6NR and 616. Remove 615, 6AA, 6NF and 6NK

Check out this [thread on BImmerfest.com](https://www.bimmerfest.com/forums/showthread.php?t=755779) for more info.

FYI this is for NBT only, and will not work for NBT Evo head units.

**Comment by jezikk82** [comment]
I saw that topic but as i mentioned its only for the Old unit. What i heard and asked is for the new headunit nbt evo and entrynav.

**Comment by ericgla** [comment]
My bad, you did mention a telematic module, which is only used by the NBT Evo.  The only information I've seen via the forums is that internet over BT is not possible for the Evo.  If you have a link to the app you mentioned please post it.

**Comment by jezikk82** [comment]
Unfortunatelly i dont have this App and russian forum link i have dont exists anymore. On bimmer fest forum in one of threats somebody else mentioned that aswell.

**Comment by hufman** [comment]
Interesting, I didn't know about this feature! My car doesn't support any weather map or telematics at all.
I haven't found any APIs to do as you suggest, to upload custom weather data into the car. I can only affect things within my own app entries in the car, while the weather functionality would be a functionally separate app. It sounds like the weather app runs entirely in the car, too, while I only have access through the phone's remote app functionality, and so I would only possibly be able to alter any BMW apps on the phone.
Sorry about that!

**Comment by jezikk82** [comment]
Can you share some information how I can debug the connectivity and API you found.  I can try to dig into that, but before I have to lunch successfully the app in my car.

I saw "similar" app up and running in one Russian guy with NBT_Evo ID6. He told me that it work like a proxy between the car and BMW servers to provide date with are free.  Also he told me that in next revision it'd be possible to use different weather and search provider.  

So somehow they manage to overwrite the internet connectivity settings in HU to use phone internet tethering. If the phone is not connected or have not an internet connectivity HU just stated "No connection" error.  He was not a tech guy so i didnt manage to get more info.

**Comment by jezikk82** [comment]
https://bmw.spoolstreet.com/threads/anyone-thought-of-building-a-connected-drive-server.1512/
https://bmwi3owner.com/2016/01/secrets/
https://github.com/edent/BMW-i-Remote/#servers
https://community.smartthings.com/t/beta-release-bmw-connecteddrive/122165

**Comment by jezikk82** [comment]
https://www.bmwclub.ru/categories/avtomobili-bmw.145/

This is the Russian forum I was talking about.

**Comment by hufman** [comment]
I'm going to close this, because it's not within this project's scope (replicating Android Auto features as IDrive apps).

**Comment by jezikk82** [comment]
Ok, but I talked with some friends who I introduced the app and they like it. But to replikate missing connected services it would be also nice to have whether service avaliable in the car for current location and also temporarily for location of the destination.
