### ISSUE TITLE
1.3rc2 release worse performance than 1.2.2 from May

### ISSUE THREAD

**Issue by sandrik93** [hufman/AndroidAutoIdrive#353]
I was using the May release of 1.2.2 (just in case tried both sentry and nonanalytics builds) and apart from already mentioned issues it worked great. I mainly use it with Spotify and Podcast Addict and both apps worked as expected. As soon as I switched to the 1.3rc2 it started bugging out pretty badly. It seems like the connection is very unstable and laggy. Sometimes if "next song" is clicked, it will not do anything and then go to a next song in about 30 to 45 seconds. The rest of the connection, to Spotify in particular, is very bad. It takes minutes from the start to establish connection, song details will hang up and not change even if the new song is playing (including play time graphic/bar not moving and album art staying the same). Similar can be said about Podcast Addict. Very spotty and laggy connection. As soon as I downgraded back to 1.2.2, it all started working great again. All in all, it quite unusable in the latest release (for me).

**Comment by hufman** [comment]
I'm sorry to hear that! To be clear, do you mean the [1.2.2 release from August](https://github.com/hufman/AndroidAutoIdrive/releases/tag/1.2.2)? Or a nightly build that you downloaded in May which may have included 1.2.2 in the filename and would also include a hexadecimal reference to the last commit it included?

Perhaps you were experiencing #254, which exhibits similar symptoms? Does the responsiveness recover if you kill Spotify and reconnect? I haven't heard of any problems with Podcast Addict, could you share a video to show that experience?
If the Handler thread has crashed somehow, periodic updates would indeed fail, but it should trigger a full update each time you open the playback screen. Do you see any successful screen updates as you enter the music app in the car? I haven't seen any new crash reports come through, so it may not be this.
Do you see any error messages in the `adb logcat` output?

**Comment by sandrik93** [comment]
Nightly. Specifically - 1.2.2-445-5e0a51c from May 15th. Responsiveness does not recover if I kill Spotify. I was tinkering with it for about 15 minutes but couldn't catch a specific pattern of when it works and when it doesn't. It didn't work most of the time though. 
I haven't looked at the log

**Comment by hufman** [comment]
I struggle to find any difference from [5e0a51c through 1.3rc2](https://github.com/hufman/AndroidAutoIdrive/compare/5e0a51c...1.3rc2) that would affect this. I do know that [since 1.3rc2](https://github.com/hufman/AndroidAutoIdrive/compare/1.3rc2...master) the Spotify SDK has been updated and that seemed to help other users with their Spotify experience: do the current nightlies work better for you?

**Comment by sandrik93** [comment]
Current nightlies work the same way s the 1.3rc2.

**Comment by hufman** [comment]
I would greatly appreciate further testing. Some other things to check include:
- Are you running the official Spotify version or a mod? What version of Spotify, latest or some older version?
- Does it perform better if you revoke the permission to browse your library? It won't be able to start Spotify and the cover art will be flaky, but it will use a different API for metadata updates.
- Can you share pictures or video of what it looks like and how it behaves?

**Comment by hufman** [comment]
I believe MyBMW upgraded over the weekend, do you see any change in behavior?

**Comment by sandrik93** [comment]
I went with 1.3 release to see if it does the same thing. It did. Then I saw that battery optimization was on. Turned it off, reconnected. So far so good. Will keep monitoring.
Also, I noticed that when using "turn shuffle on/off" in Spotify, after I click it I end up in the "Actions" submenu where you have shuffle, repeat, seek and all that. Didn't do it in earlier versions. Is that deliberate or..?
And thanks again for overall great app.

**Comment by hufman** [comment]
Ah that could be. I greatly appreciate the testing across the diversity of Android devices!

Good catch! I just pushed up a change that should fix this, but I am unable to test it this week. The Legacy and Spotify player views happen to share some action handlers, and so when I added the ability to show the Legacy view in new cars, this action handler was incorrectly reused.
