### ISSUE TITLE
"App" menu missing on car

### ISSUE THREAD

**Issue by donsaimon** [hufman/AndroidAutoIdrive#354]
Today a new issue happened to me. All was OK but the app said to enable app menu on my car... And no music nor apps connection... How to enable it? It was automatically enabled, now I do not see the voice "app" on the car menu, but Bluetooth voice only...

**Comment by hufman** [comment]
That sounds like the car wasn't able to update your BMW Connected subscription status, can you check in BMW Online or in MyBMW for whether this subscription is active and then ask the car to update it's subscription status (perhaps outside of any parking garage it may be in)

**Comment by donsaimon** [comment]
In Connected drive app It is reported that ConnectedDrive services are active...

Da: ***@***.***
Inviato: 28 Luglio 2021 20:57
A: ***@***.***
Rispondi a: ***@***.***
Cc: ***@***.***; ***@***.***
Oggetto: Re: [hufman/AndroidAutoIdrive] "App" menu missing on car (#354)


That sounds like the car wasn't able to update your BMW Connected subscription status, can you check in BMW Online or in MyBMW for whether this subscription is active and then ask the car to update it's subscription status (perhaps outside of any parking garage it may be in)

**Comment by hufman** [comment]
Hmm I can't help much in this area, my car doesn't have a subscription process. You should ask your BMW dealership or contact their support system.

**Comment by donsaimon** [comment]
Ok thank you.
I have tried to uninstall and install again Connected Drive app. Let's see what happens...

Da: ***@***.***
Inviato: 28 Luglio 2021 21:19
A: ***@***.***
Rispondi a: ***@***.***
Cc: ***@***.***; ***@***.***
Oggetto: Re: [hufman/AndroidAutoIdrive] "App" menu missing on car (#354)


Hmm I can't help much in this area, my car doesn't have a subscription process. You should ask your BMW dealership or contact their support system.

**Comment by donsaimon** [comment]
Ok problem solved.
Uninstall and re-install ConnectedDrive app worked.
