### ISSUE TITLE
Connection unstable

### ISSUE THREAD

**Issue by Simmo500** [hufman/AndroidAutoIdrive#357]
Firstly, thank you so much for this app. It has completely transformed my experience in my F31.  My issue is an unstable connection. Everything generally connects up perfectly when I get in the car, but around 5/10 minutes in the connection drops, all apps disappear including the notification option. 

 I can not get it back even through disconnecting/ connecting Bluetooth. The only way I have found that sometimes works is by restarting my phone, or force stopping the app and restarting again.

  Any help to make it more stable would be amazing.

**Comment by hufman** [comment]
Good morning! I'm glad you like it.
That sounds like Android is killing the connection in the background. Do you see the notification icons at the top from both MyBMW and AndroidAutoIdrive? Do you have a phone that is especially aggressive in killing background processes, you may need to exempt these apps from background processing restrictions. What phone and OS and app versions are you running?

**Comment by Simmo500** [comment]
Hi Walter,

Thanks for your reply.

I'm using an Oppo X2 find Neo running Android 11.

When it disconnects, strangely both AndroidIdrive icon and MyBMW icons are showing in my notification tray as running and connected.

Also, if I open the Android app, it displays everything as normal and connected , however in the car that's not the case!

Thanks again for your help.

Kind regards,

Mark

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Simmo500** [comment]
Just having a look at the settings, the 'allow background activity' option is unchecked, would it make sense to turn this on? Or maybe it won't make a difference? 


![Screenshot_2021-08-01-21-14-03-12_b7ff6dd0e181029d8492f0876df908d6](https://user-images.githubusercontent.com/88284524/127784204-2a1573bd-5126-48d9-90ff-e607d6a6dd4f.jpg)

**Comment by hufman** [comment]
That would be a good thing to try, let me know how it goes!

**Comment by Simmo500** [comment]
Hi Walter,

So far so good! Changed that setting and driven around 2 hours with no connection issues today, hopefully that's that!

Thanks for your help!

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by hufman** [comment]
I'm glad to hear it! I had added a checkbox to the app to warn when background execution is disabled, but perhaps your phone has a different method that isn't being detected.
