### ISSUE TITLE
Spotify Playlist and Soundcloud

### ISSUE THREAD

**Issue by Shokwaves84** [hufman/AndroidAutoIdrive#363]
AndroidAutoIdrive:  1.3
Spotify: Version 8.6.44.851
Soundcloud: Version 2021.07.13-release

BMW G31 08/2018

I am so grateful for your App

Soundcloud:

since the update of AAI 1.3 Soundcloud is no longer displayed in Idrive.the mobile phone settings for Soundcloud and Spotify are correct and unchanged. 

AAI App Settings Musik Soundcloud not available

that makes me sad because I used Soundcloud very often and it always went well before the update

Spotify:

I have a playlist with 200 songs and the same 20 songs are always played on the list. always the same songs!

no other songs are shown in the list either. 

(I don't have a Spotify premium account)

I hope you can give me some advice and I apologize for my bad English

Thank you very much again for your great work and your app

regards Fabian

**Comment by hufman** [comment]
I'm glad you enjoy it! Thank you for the detailed report.
The problem with Soundcloud is actually that Soundcloud has disabled access for other apps to launch it, starting with version v2021.08.12. If you downgrade to [v2021.08.11](https://apkpure.com/sound-cloud-android/com.soundcloud.android/download/87080-APK-500e8e116f80cf0c2113c6a1863427fc?from=versions%2Fversion) and then swipe down in the music list to rescan the apps, it will work again. Make sure to configure the Soundcloud app in the Play Store to disable automatic updates.

I haven't seen that Spotify behavior before, can you share the specific playlist you see it in? Does it show a repeating list, or does it only play a few specific tracks no matter what you select? I know the Liked Songs and the dynamic Artist tracks playlists are buggy, are you seeing the same behavior in a regular playlist?

**Comment by Shokwaves84** [comment]
many thanks for your quick response and help


Soundcloud: 

I have downgraded Soundcloud and it now appears again in the AAI app

when I drive my car later I will test whether Soundcloud is displayed again in the idrive

Spotify Playlist:

https://open.spotify.com/playlist/7u1jfBRKxvQ9TQLRv5fzgA?si=iP7kpTpVQkCeMTHDSQcccw&utm_source=copy-link&dl_branch=1


However, it does not only affect this one playlist but generally all playlists! 

i never see the whole list in the Idrive but always only a certain part of the songs.  (about 20 same songs in constant repetition) 
I also can't choose any other song because I only ever get a fraction of the list in the Idrive.

when i listen to an album i also get other artists played in between.

I thought it might be because I don't have a premium account?!


one more question:

In the future, it will be possible to search directly in the idrive for interpreters that have not yet been saved in my library? in other words, a completely normal search as one is used to from a mobile phone?


thanks again for your efforts and again sorry for my english. I wish we could talk in German to better describe my problem🤦‍♂️

have a great weekend

**Comment by LACNR** [comment]
I think when you don't have Spotify Premium you are not allowed or only limited to play individual songs on mobile devices, at least that's how it was 5 years or so ago.

But it's strange if it really repeats the same 20 songs, though there's button that lets you repeat each Songs one time and/or unlimited times.

Du kannst es mir sonst auf deutsch schreiben @Shokwaves84

**Comment by Shokwaves84** [comment]
okay, thank you very much for the help. I will keep testing it. I also think it's because of spotify premium

In any case, I'm glad that Soundcloud is working again
