### ISSUE TITLE
Improve the phone UI about unavailable apps

### ISSUE THREAD

**Issue by hufman** [hufman/AndroidAutoIdrive#40]
The list of music apps shown in the phone display does not clearly show that some apps are not available for control, which causes disappointment when users see a list of music apps on the phone and an empty list in the car.
The unavailable apps should be crossed out or greyed out in some way.
Additionally, perhaps it could provide a recommendation to install some working apps.

This would prevent future instances of #37

**Comment by jezikk82** [comment]
Could you add Mi Music to the list of apps. It's working and can be controlled by the app but is not shown. Also, current version on Spotify is working with BMW connected classic app. Lated I will add photos.

**Comment by hufman** [comment]
![image](https://user-images.githubusercontent.com/1592375/69904525-6293e500-135c-11ea-9e99-05d30228330c.png)
There are now icons that specifically show an app is unavailable, and the capabilities icons can be clicked to expand them to a description.
