### ISSUE TITLE
Additional info in Debud mode

### ISSUE THREAD

**Issue by jezikk82** [hufman/AndroidAutoIdrive#55]
Hi,
I'd be good to have in Debug version of the app information as follow somewhere at the bottom of the main screen (just above the "connected to car":

- build version with date and time
- car screen resolution capabilities["hmi.display-width"] x capabilities["hmi.display-hight"]
- ability to turn or always on local log file (in device) to get all debug information on the fly -with click shortcut to open it
- if gmap enabled FPS rate (if possible)

**Comment by hufman** [comment]
![image](https://user-images.githubusercontent.com/1592375/77243438-303a1c00-6bc7-11ea-8836-47b1d38a06b3.png)
Added a build version and a list of reported car capabilities to the SetupActivity that appears when you click the Car Is Connected bar at the bottom of the main screen.

**Comment by hufman** [comment]
![image](https://user-images.githubusercontent.com/1592375/87390363-91fb0900-c55d-11ea-8b92-90b8cc121e71.png)

Added the BCL tunnel performance statistics, as reported by the main Connected app
