### ISSUE TITLE
Implement global multimedia coverart and position

### ISSUE THREAD

**Issue by hufman** [hufman/AndroidAutoIdrive#59]
The official Spotify app shows the progress and the cover art in the multimedia sidebar.

**Comment by hufman** [comment]
I suspect this is related to the IDrive5+ audioHmiState feature, which will take a while to learn.

**Comment by hufman** [comment]
![image](https://user-images.githubusercontent.com/1592375/74707639-30618900-51cf-11ea-9741-fc2fd2d87012.png)

Mostly works, but the icons can't be uploaded with the new cert

**Comment by jezikk82** [comment]
Looks promising.... Nice work.

**Comment by hufman** [comment]
I think this can't be done satisfactorily until I find a cert with both the old Audioplayer icon pack and the new multimedia_v3 ui_description.xml :( I'll keep the branch around as an early start, at least.
