### ISSUE TITLE
Choose which music apps to display

### ISSUE THREAD

**Issue by mfisher224** [hufman/AndroidAutoIdrive#60]
Is there a way to disable some of the apps from showing in the car? For example, I have Plex installed, but do not need it showing up in iDrive.

**Comment by hufman** [comment]
Please try out [this dev build](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/395/395.1/app/build/outputs/apk/nomapNonalytics/release/androidautoidrive-1.2.1-28-e996318-e996318aae1abbeed708989dadcb6c7deea56544-nomap-nonalytics-release.apk) and see if the swiping behavior works well for you!
