### ISSUE TITLE
Instrument cluster shows Not possible BMW i3 NBT ID4

### ISSUE THREAD

**Issue by ziggythehamster** [hufman/AndroidAutoIdrive#63]
I think this is happening because it looks like you're only setting the currently playing track, and on my car, the cluster doesn't show anything unless you begin to scroll with the steering wheel. If you set the previous and next items, maybe it would work (these could be "Back" and "Next" and just do the same as the app buttons). No Android official app that I'm aware of uses this correctly, and iOS Spotify only shows the current song with nothing else scrollable (and is therefore useless). Bluetooth audio also lacks this feature.

Also, sorry if I'm filing too many issues - I love that you've RE'd this and can't wait to get time to dig into the app and submit some PRs ;)

**Comment by hufman** [comment]
The code for this functionality is collected in [GlobalMetadata](https://github.com/hufman/AndroidAutoIdrive/blob/master/app/src/main/java/me/hufman/androidautoidrive/carapp/music/GlobalMetadata.kt). I do only send the current song, but I _think_ that's for the Multimedia side panel. I also send a queue to the instrument cluster, and even generate a placeholder queue with Back and Next entries if the app doesn't provide a queue.
However, Spotify does typically provide a queue, so it should definitely be running the logic to populate the full queue to the instrument cluster.

I was not able to test this thoroughly with my previous IDrive4 Mini: I observed that the official Spotify app would call this same logic to send a queue to the car, but that the car was not showing any queue in the instrument cluster. With this current IDrive5 Mini, I was able to flesh out this implementation, but I no longer have the IDrive4 car to test on :)

What I suspect is happening is that the instrument cluster playlist is tied into the audio context. In Bluetooth mode, my car only shows the current song and instantly switches track when I push a steering button, unless I set my app to claim audio context, and then my queue logic succeeds.

I fear that doesn't help you very much. I had decent success with Bluetooth on my IDrive4 car, with it properly skipping tracks back/next with the steering wheel controls.

I wish I knew a better answer!

**Comment by ziggythehamster** [comment]
The i3 is weird - it only shows the playlist if you attempt to scroll, and only selects on press. There's no back/next on the steering wheel, but there is a back/next on the hardware shortcut button bar (and it works fine). On Spotify Connected iOS, you can't back/next but the scroll wheel will show the current song and pressing will pause. But no Android app works that I've tried. I'm wondering if the i3 cluster uses a weird argument that other cars don't use because AFAIK it is the only one which doesn't have a section for currently playing media. Does the debug build have any functionality to send arbitrary stuff to the IC for testing?

**Comment by hufman** [comment]
Very curious! Digging around the Spotify iOS widget layout, it doesn't even have an instrument cluster playlist, it only has the multimediaInfoEvent.
I'll try to come up with some way to record what the iOS app is saying, and that should give me a better idea of how I can copy that behavior.
The debug build isn't any different, functionally, it just has different signing keys. I use a set of easily-editable private apps to test specific scenarios easily.

Thanks for finding this bug!

**Comment by hufman** [comment]
I'm going to close this as unsupported, I believe it is due to the missing audio context with Bluetooth and ID4. The iOS success is due to being able to run the app and the audio context through the USB cable. With an audio context (a new car and Bluetooth apps connection), my tests with the Spotify queue in the instrument cluster works well.
