### ISSUE TITLE
Notifications: Correctly handle emojis 

### ISSUE THREAD

**Issue by masteralarm** [hufman/AndroidAutoIdrive#64]
iDrive seems to have problems showing emojis (at least my ID4 system).

It would be great to incorporate a function to replace emojis with text in notifications, for example:
😀 => `:grinning:`
😉 => `:wink:`

There are already libraries available that should help with that, for example: [https://github.com/AniTrend/android-emojify](https://github.com/AniTrend/android-emojify)
or its origins
[https://github.com/vdurmont/emoji-java](https://github.com/vdurmont/emoji-java)

**Comment by hufman** [comment]
This is great, thanks for the idea!
