### ISSUE TITLE
Coding 6NR

### ISSUE THREAD

**Issue by onix45** [hufman/AndroidAutoIdrive#66]
If a car does not have 6NR from factory (VIN: D954763) and i would code the 6NR into the car, but without an FSC code (that you have to buy from BMW probably), would this app work?

**Comment by onix45** [comment]
Also, this particular car has option 6AK, which as i understand incorporates/replaces 6NR, but your app sadly does not work.

**Comment by hufman** [comment]
I'm not sure on the specifics, but [this BMW page](https://community.bmw.com/t5/Vehicle/My-vehicle-does-not-show-any-quot-BMW-Apps-quot-function-under/ta-p/18180) indicates that either option should work. It mentions a specific Navigation option, perhaps you need to enable that one too? Do the official apps work?

**Comment by onix45** [comment]
I do have the navigation system professional option, from factory.
Maybe the problem is that the car is a US import to Europe, so the telemantics module SIM card might not work. Or maybe i need to code enhanced bluetooth?
I have never tried the official apps, since i know that i do not have an active sim card in the car, so they would not work. But i guess i do not nee the official apps to actually have an internet connection to make your app work.

Alos i whould add that i have updated the idrive software via usb drive to the latest available version from bmw's page.

**Comment by hufman** [comment]
It looks your car was built in 2014, so it may have an IDrive that is too old to support Android. The one generation before IDrive 4 only supports BMW Apps on iPhone, I'm afraid. I'm not sure how to tell the version, except for some subtle theme differences.

By official apps, I refer to the BMW Apps that come with BMW Connected, such as the Calendar. When you plug your phone in, BMW Connected should detect the connection, it should update the phone screen with the current fuel level and mileage and car photograph, and BMW Calendar should show up in the car's ConnectedDrive menu. My app works over this same local connection, which doesn't need any telematics connection to function.

Check that the official apps work, from either Android or from a friend's iPhone, and we'll figure out what's happening!

**Comment by onix45** [comment]
Yup, the connected app does not update the calendar or the fuel level when i connect my android phone to the car. It does however show the little icon on top that says the car is connected, but nothing else happens. Will see if anyone i know has an iphone.

**Comment by hufman** [comment]
I'm going to close this because I can't help much with coding issues, unfortunately.
