### ISSUE TITLE
Cannot build project in Android Studio

### ISSUE THREAD

**Issue by Laurens0619** [hufman/AndroidAutoIdrive#68]
Hi,

I am trying to build the project in Android Studio but I am getting errors on the references projects IDriveConnectKit and IDriveConnectKitAndroid.

I tried the src from releases, clone, git download but still got the same error.

the IDriveConnectKit folders are also empty so I think something is going wrong with my references. Any hints?

**Comment by masteralarm** [comment]
Seems to me that you did not checkout the submodules:
`git submodule update --init`

**Comment by Laurens0619** [comment]
That did the trick, thank you very much :)

For future reference:
1. git clone https://github.com/hufman/AndroidAutoIdrive.git
2. cd AndroidAutoIdrive/
3. git submodule update --init
