### ISSUE TITLE
Old Spotify used to support browsing and now doesn't 

### ISSUE THREAD

**Issue by ziggythehamster** [hufman/AndroidAutoIdrive#70]
This is a weird bug. Browse used to work with this old Spotify version, and then the only thing that changed between when I know it worked and now is that I did a pending Android update. I was on 9, and am still on 9, but with the Dec 2019 security update. It might have worked since the update, I don't recall exactly when it stopped working because I don't use Browse often. This app detects that it supports browsing, but under browse, it now says No Data. Maybe some Samsung crapware updated and it thinks it's blocking something for security?

Maybe this is a non issue since I see you are soon to replace the Spotify integration, but thought I'd file the bug anyways just in case someone did have this happen.

**Comment by hufman** [comment]
One thing to check is whether it automatically upgraded your Spotify to the latest version from the store, even though you manually installed the old version. In which case, you'll need to uninstall the store version and reinstall the older version.
Alternatively, you could try testing the new app version with Spotify API support! [Sentry](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/338/338.1/app/build/outputs/apk/nomapSentry/release/androidautoidrive-1.2-42-60284fc-60284fcede71fe94075251f3fe76103db9ef9d97-nomap-sentry-release.apk) or [nonalytics](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/338/338.1/app/build/outputs/apk/nomapNonalytics/release/androidautoidrive-1.2-42-60284fc-60284fcede71fe94075251f3fe76103db9ef9d97-nomap-nonalytics-release.apk)

**Comment by hufman** [comment]
The new version of the app has been published, bringing the new Spotify API method for browsing. I think this provides another way to solve this bug, so I'll close it for now.
