### ISSUE TITLE
apps showing and working but no audio, only bluetooth audio

### ISSUE THREAD

**Issue by sanderlv** [hufman/AndroidAutoIdrive#73]
Having connection with the car, can see app, can control but audio not playing when app selected. Only when external device is selected again. Latest version 1.2.1 installed with classis connected app.

**Comment by hufman** [comment]
This sounds like the Request Audio Focus box is checked, but your phone is connected over USB. Try unchecking that and leaving the car listening to Bluetooth, does that work better?

**Comment by sanderlv** [comment]
Not sure what request audio focus then exactly means but will try today.

**Comment by hufman** [comment]
Did this help? I implemented a change for the next version which should reduce this confusion, by automatically using the Audio Focus only in the working scenarios.

**Comment by hufman** [comment]
The new version was just released which handles audio context much more automatically, which should fix this.
