### ISSUE TITLE
Decipher the chassis code

### ISSUE THREAD

**Issue by hufman** [hufman/AndroidAutoIdrive#79]
It would be feel more personal to have the app say what kind of car it is connected to

**Comment by hufman** [comment]
@bogdan-calapod Could you submit a PR with the chassis names, like the enum we talked about? And then I'll add the UI part for this.

**Comment by bogdan-calapod** [comment]
Sure - I'll do it this week, as soon as I get an hour or two to get to it 😁

**Comment by bogdan-calapod** [comment]
Opened #80 - let me know what you think :D

**Comment by jezikk82** [comment]
You are missing the newer F-series and whole G and I series. 

E.g. 
G01 - BMW X3
G02 - BMW X4
G20 - 3 series
G21 - 3 series wagon
G30 - 5 series
G31 - 5 series wagon

**Comment by bogdan-calapod** [comment]
@jezikk82 thanks for the heads up, will add these ones as well.

Any idea of where I could find a complete list of them ?

**Comment by jezikk82** [comment]
https://www.turnermotorsport.com/t-BMW-Chassis-Codes
https://www.bimmerworld.com/About-Us/BMW-Chassis-Engine-Codes/
https://burgertuning.com/pages/chassis-codes

This 3 list looks much more up2date.

**Comment by bogdan-calapod** [comment]
Thanks @jezikk82, will integrate the burgertunning link, as it does look the most complete of the three.

**Comment by hufman** [comment]
![image](https://user-images.githubusercontent.com/1592375/87081631-8a92d300-c1de-11ea-9f3e-130e7667b71b.png)

**Comment by hufman** [comment]
Available in [this dev build](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/414/414.1/app/build/outputs/apk/nomapNonalytics/release/androidautoidrive-1.2.1-46-454a9a4-454a9a4536cab2e7f52bb6e41a46148f674c5bc9-nomap-nonalytics-release.apk).
