### ISSUE TITLE
CIC system compatability

### ISSUE THREAD

**Issue by Edgaras91** [hufman/AndroidAutoIdrive#84]
Hi, Is this compatible with CIC systems, (also have S609A- Navigation system Professional)?
If so, what steps should I follow to try this out?
I am able to code the car if needed.

Also using an Android phone, would that work too?

**Comment by hufman** [comment]
Thanks for reaching out! I believe CIC is only compatible with iPhone, but you can test easily: Plug in your Android phone with the BMW Connected App installed and check if the app connects and your car shows some new entries in the Connected menu such as the Calendar.
If that works, than this app will work too.

**Comment by Edgaras91** [comment]
Thanks, I already tried that and it didnt recognise, so I think you are right. Thanks for fast response!
