### ISSUE TITLE
Mini Connected Classic app never connects.

### ISSUE THREAD

**Issue by TheDevFreak** [hufman/AndroidAutoIdrive#91]
I could reach the screen with the progress bar between the phone and the car on the app however the app would then simply crash everytime.

Using an APK i found for version 5.0 of the "new" app made it work - just wondering if anyone else had ever experienced this with the classic app and anything they could do about it?

OnePlus 7 on Android 10 fwiw.
Car is a 2020 Mini Electric

**Comment by hufman** [comment]
Congrats on your new Mini Electric! I'm still waiting in line for mine :)
The Connected Classic app only needs to be installed to provide the security service. It does not properly support the current Android memory management, and so the new Connected app should be used to provide the tunnel connection to the car.
In your situation as a Mini driver, I recommend installing Mini Connected (and gain all the remote functionality it provides) and then install BMW Connected Classic for the security service.
Alternatively, you should try out the [release candidate](https://github.com/hufman/AndroidAutoIdrive/issues/27#issuecomment-663220896) for the next release version, which no longer needs the Connected Classic app to be installed.
Let me know if that works for you!

**Comment by TheDevFreak** [comment]
Interesting, I could never get BMW Connected Classic to talk to the car. :/

Am i supposed to use the latest Mini Connected alongside BMW Connected Classic and not really expect to see anything in the classic app happen in terms of a connection?

I'll try the RC soon.

**Comment by hufman** [comment]
That is correct! The Classic app only needs to be installed, it doesn't ever need to be signed in or connected to the car directly, just that this app can ask it to answer security challenges as needed.

**Comment by bogdan-calapod** [comment]
@hufman I guess this issue can be closed, given the fact that the new version doesn't require the classic app, right ?

**Comment by hufman** [comment]
Indeed! Thanks for catching that haha, I'll close this out now.
