### ISSUE TITLE
Spotify song metadata is blank on fresh start

### ISSUE THREAD

**Issue by hufman** [hufman/AndroidAutoIdrive#93]
The global metadata from the Spotify app sometimes is empty. Switching to a different app and then back to Spotify fixes it.
Switching songs shows the proper metadata and then it goes blank again.

**Comment by hufman** [comment]
Another clue: The IC song selection displays the current song but doesn't [restart it when clicking](https://github.com/hufman/AndroidAutoIdrive/commit/fc5fb1d2e30443cd2bef667f224ef50e46b01e15).

**Comment by hufman** [comment]
I believe this is because the Connected Spotify app is updating its playback progress to the car, even though it isn't the active app. The latest version of Spotify does not seem to show this behavior. I haven't yet figured out why the car stops showing this blank screen after switching apps.

**Comment by masteralarm** [comment]
> The latest version of Spotify does not seem to show this behavior. 

The latest version of the Spotify app for Android seems to have dropped support for the iDrive integration.

see  [https://community.spotify.com/t5/Other-Partners-Web-Player-etc/BMW-Connected-Drive-deprecation/m-p/5011216#M71993](https://community.spotify.com/t5/Other-Partners-Web-Player-etc/BMW-Connected-Drive-deprecation/m-p/5011216#M71993)

**Comment by hufman** [comment]
I think this will be fixed with #103 since my app will be posting its own global metadata

**Comment by bogdan-calapod** [comment]
This can be closed as well I think - or is #103 not merged into master yet ?

**Comment by hufman** [comment]
Yeah I believe this can be closed. It has been merged, but mostly the problem disappeared on its own because the official Spotify stopped supporting the car protocol.
The only situation that it would come up now is if a user has downgraded to an old version of Spotify to enable Searching through MediaBrowserService support. Once #104 is implemented, there should be no reason to run anything older than the latest version of Spotify, and this problem will never exist again :)
