### ISSUE TITLE
Trim/replace emojis in Spotify playlists ?

### ISSUE THREAD

**Issue by bogdan-calapod** [hufman/AndroidAutoIdrive#94]
I like to use emojis in naming Spotify playlists, as they help with finding playlists faster. 

The in-car system doesn't seem to support them though (they show up as Chinese characters) - I know AndroidAutoIdrive replaces emojis with text descriptions in notifications. Would it be possible to do this for Spotify playlists as well ?

**Comment by hufman** [comment]
Sad news! The official Connected app does not replace all emoji characters with the REPLACEMENT_CHAR, it's that some emoji just happen to line up with CJK characters and some do not. This collection of emoji I found ([emoji😀😃😄😁😆😅😂🤣☺️😊😇🙂🙃😉😌😍🥰😘😗😙😚😋😛😝😜🤪🤨🧐🤓😎](https://open.spotify.com/playlist/3ibDD1KCG5iK23A2P5s9RA)) shows the same pattern in AndroidAutoIdrive's Spotify interface, the official Connected Spotify interface, and in the Connected Calendar :(
![image](https://user-images.githubusercontent.com/1592375/89864763-602b9100-db61-11ea-8b24-f73be11c39fe.png)

I'll set up emoji replacements for the music browse functionality, it shouldn't take long.

**Comment by hufman** [comment]
[Dev build](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/479/479.1/app/build/outputs/apk/nomapNonalytics/release/androidautoidrive-1.2.1-101-0b55092-0b550920c10c63ab238868b731aa0925e4a2afd7-nomap-nonalytics-release.apk)

**Comment by bogdan-calapod** [comment]
I'd say that this is fixed :D
