### ISSUE TITLE
Better podcast management in Spotify

### ISSUE THREAD

**Issue by bogdan-calapod** [hufman/AndroidAutoIdrive#96]
Currently the experience with Podcasts isn't as good as it is with regular playlists.

I see the following pain points:

- [x] Opening a podcast with a long list of episodes does not show the full list, neither in the "Now Playing" tab, nor in the instrument cluster screen (both display the latest 15 episodes or so)
- [x] Selecting an episode to play is a bit wonky - it seems to always try to play the last episode, regardless of what episode is actually clicked on
- [x] In the regular playlist mode, we have handy "< Back" and "Next >" options in the instrument cluster screen. It would be nice to have "< Skip 15 seconds" and "Forward 15 seconds >", as well as the regular "< Back" and "Next >" buttons in the instrument cluster. (Note: the back and next options in the iDrive menu work fine)

I'm using Spotify v8.5.70.868.

Funnily enough the "Podcasts" option from the "Search" tab works fine to start playing the last played/latest episode (Spotify decides on that correctly I guess) 😁

**Comment by hufman** [comment]
This seems to be a limitation of the Spotify App Remote library :(
The older Spotify version with MediaBrowser access provides a nice list of episodes, 1-70 of the Darknet Diaries for example. The Spotify API access only returns the most recent 30 episodes, though I [ask for 100](https://github.com/hufman/AndroidAutoIdrive/blob/e95903d/app/src/main/java/me/hufman/androidautoidrive/music/controllers/SpotifyAppController.kt#L173). Even the ListItems pagination insists that there are only 30 results!
As for jumping to an episode, the API suggests this [skipToIndex](https://github.com/hufman/AndroidAutoIdrive/blob/e95903d/app/src/main/java/me/hufman/androidautoidrive/music/controllers/SpotifyAppController.kt#L224) function. I have some wrapper code to try to find the index for the selected item, but the index seems to be completely ignored and it starts playing the earliest episode instead.
I'll report these bugs to the Spotify API plugin and hopefully they'll look into it!

The Skip navigation is a very clever idea! I'm not yet sure how that should work, I don't have a clean and generic way to determine if the app is in podcast mode to add those extra options. Other dedicated audiobook and podcast apps just use the normal back/next buttons to seek a short time, in my experience, so I hadn't considered such functionality.
Do you know about long pressing on the dashboard back/next buttons? With Bluetooth app support, not only does the instrument cluster reflect this app's information, but the back/next buttons (including long press) are handled too, and it starts a seeking procedure if you hold the buttons down.
I do want to figure out something though, especially for users with USB who don't have the instrument cluster or the hardware buttons for seeking.

Playing a podcast from the Browse interface does seem to jump right to the most recently-playing episode, but that is indeed Spotify doing things itself.

**Comment by bogdan-calapod** [comment]
> This seems to be a limitation of the Spotify App Remote library :(

Ah, that's a shame :( So it's basically on Spotify's side - at least we know where the problem is 😅

> Do you know about long pressing on the dashboard back/next buttons? 

Gonna try it and will let you know if it works. I guess you are referring to the default Bluetooth controls of iDrive, right ? Not the "Audioplayer" app.

**Comment by masteralarm** [comment]
> I'm not yet sure how that should work, I don't have a clean and generic way to determine if the app is in podcast mode to add those extra options.

I think you could use the the current `Track` from the `PlayerState` to get information on the currently playing track. The track class has a Boolean `isPodcast` that, well, does what you expect 😉 (at least I hope so, with Spotify you never know....)

**Comment by hufman** [comment]
@bogdan-calapod I refer to the left/right arrow buttons next to the hardware shortcut buttons, in the bottom right of this image. I don't believe the Bluetooth source supports long-press to seek, but the Audioplayer source (with audio context) handles it.
https://www.carkeys.co.uk/media/14041/what_is_bmw_idrive_guide_1.jpg?center=0.46590909090909088,0.47148288973384028&mode=crop&width=1200&height=800

@masteralarm Oh interesting! Thanks for finding that, that should be perfect. I could imagine that the SpotifyAppController's skipBack and skipNext functions could alter their behavior to emulate the seeking behavior of other podcast apps, in the case that the current track is a podcast. I can add that after the queue behavior gets fixed, to still allow for changing episodes through the car interface.
Propagating the `isPodcast` detail up through the layers to the GlobalMetadata class to add the manual seek controls would be harder and messier to do for this one exception, so I'd still want to come up with a general seeking interaction.

**Comment by bogdan-calapod** [comment]
I just tried with the arrow buttons and indeed it seeks forward/backwards. That's really cool - didn't know that was possible :D

**Comment by hufman** [comment]
I wrote up #97 to plan out new seeking options.

**Comment by hufman** [comment]
Perhaps related, the Spotify Liked Songs playlist exhibits a similar Play Queue Item behavior: Selecting any entry from the Queue View seems to play the most recently Liked song, and not the song that was selected.

**Comment by bogdan-calapod** [comment]
A recent update from Spotify has changed the Previous/Next functionality so that it automatically skips 15 seconds :D This works regardless of what sends the media control (e.g. Bluetooth headphones, watch, etc.) so it also works in AndroidAutoIDrive nicely :D 

The first two items also seem to be fixed - episode selection works great, and the playlists seem to show all episodes, so I think we can close this one. 😀
