### ISSUE TITLE
Add notification icon in the car

### ISSUE THREAD

**Issue by hufman** [hufman/AndroidAutoIdrive#99]
Since notification popups only work in IDrive4, a different way of alerting the user for a new notification should be investigated in newer cars.

Possibilities:

- The old Online Services widget layout references a NotificationIconEvent, but attempts to trigger it in ID5 are rejected.
- The FindMate feature seems to be able to add a NotificationIcon and also show a textual notification popup, but it probably requires the BMWOne login cert

**Comment by hufman** [comment]
Here's a [dev build](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/478/478.1/app/build/outputs/apk/nomapNonalytics/release/androidautoidrive-1.2.1-100-f02ebf3-f02ebf3148106c9dbd81a2abf05f74e49e4ea030-nomap-nonalytics-release.apk) of a possible ID4 Statusbar icon.

**Comment by mbonus** [comment]
Verified working on android 10 (Aug security) Notebook is accessible through the bmw connected drive menu and head unit memory button can be assigned

**Comment by hufman** [comment]
Oh cool! Does the Book icon show up in the status bar too? May I see it action, since my car doesn't support it?

**Comment by mbonus** [comment]
![IMG_20200816_195742](https://user-images.githubusercontent.com/69769726/90346913-db29f700-dffa-11ea-9680-279133bb2821.jpg)
![IMG_20200816_195753](https://user-images.githubusercontent.com/69769726/90346925-e5e48c00-dffa-11ea-9d5f-8031fb5fa38e.jpg)

**Comment by hufman** [comment]
Thank you so much for testing for me!

**Comment by mbonus** [comment]
No prob, happy to help!  This is a really cool project!!

**Comment by chriss158** [comment]
Sadly it doesn't work on NBT Evo (Connected via Bluetooth) :( Any way i can assist you with this?

**Comment by hufman** [comment]
I suspected as much, I'll keep looking to figure out a method for newer cars. Thanks for testing!

**Comment by light4speed** [comment]
Just tested notifications on NBT2 (Evo) a idrive 6 system, and I can access the notifications under connected apps > Notification-app(Forgot the exact name). Its a new app that appears in idrive my phone is connected with AndroidAutoIDrive. However the notifications icon and normal notification screen does not show these. 

Showing as a popup or even coming through as a Offical message (that then displays on the dash) would be awesome! 

Something that may help development; if you have office enabled in idrive, notifications properly appear for text messages (when recieved as notifications on your phone). Possibly looking into how this part works could help?

**Comment by hufman** [comment]
Thank you so much for the test and ideas! I believe the Text Messages notification is related to the Bluetooth Message Access Profile, which only seems to support SMS on Android. I'll keep looking into the new notification protocol and see what I can do! I'll post a dev build here when I have some progress to share :)

**Comment by p1j0** [comment]
Hello,
I am using another app for messages, which just takes the notifications from any other app and convert them as a kind of SMS before sending them over Bluetooth to the car. This works pretty good with ID6 (and actually with any other car). The only problem is, that it works only in one direction.... 
But such option may be an improvement to the AndroidAutoIDrive for cars with ID5 and ID6 :)

**Comment by Kay0002** [comment]
> Hello,
> I am using another app for messages, which just takes the notifications from any other app and convert them as a kind of SMS before sending them over Bluetooth to the car. This works pretty good with ID6 (and actually with any other car) and you can see the notification in the original message folder, having the envelope icon also on the main display. The only problem is, that it works only in one direction....
> But such option may be an improvement to the AndroidAutoIDrive for cars with ID5 and ID6 :)

Which app are you using for messages on Idrive 6?

**Comment by p1j0** [comment]
the app name is SMS&Notifications. It is actually a Message app and one of the features it has is to forward all kind of phone notifications in "SMS format" to the car. Here is a link of its github page: https://github.com/moezbhatti/qksms

**Comment by p1j0** [comment]
It is called "Notification Forwarder Pro". It works as an standart Message app, but it just has the option to forward all kind of phone notifications in "SMS format" to the car multimedia system (model independent):
https://play.google.com/store/apps/details?id=org.groebl.sms

**Comment by hufman** [comment]
I've added initial experiments on [this branch](https://github.com/hufman/AndroidAutoIdrive/tree/bmwone_notification) to interface with the Notification Center in IDrive5+, which shows a statusbar icon with the number of messages. Try out a [test build](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/androidautoidrive-latest-bmwone_notification-nomap-sentry-release.apk) and let me know what you think!

**Comment by chriss158** [comment]
You are awesome! 🎉  This build works 👍 Thank you so much.

Some points which I noticed, on my first test:

- I assume you need the status bar app to display the icon? Can it be hidden?
- I get additionally an inbox message in the BMW message app. Is this necessary?

None of the points are real dealbreaker for me. Just asking :)

**Comment by hufman** [comment]
Thanks, I'm glad you like it :)
As I understand it, the only way to show the statusbar icon is to add a message to the Notification Center: For example, the seatbelt warning, door open warning, and new SMS messages. And so, the app now adds new notifications to the system Notification Center, currently just to show the statusbar icon, and will clear them out when viewing the main list of all Notifications. Relatedly, the BMW Connected app seems to be the only app that is allowed to post messages to this system feature (has `rhmi.notification.center=true` in its cert), so I need to log in as that app just to provide this function. I can't change the icon or text used in the Online Services list, or hide the entry in the Navigation menu, but I did hide the text name to indicate that it is not the normal BMW app!

The next step is to make the messages in the Notification Center open up the Message View screen when clicked like the normal Notification app, and then I think it'll be finished!

**Comment by Kay0002** [comment]
Notifications addition works great, thanks! If you can implement viewings messages when selecting from the Notifications area like you mentioned that would be awesome.

**Comment by hufman** [comment]
I've added click handling to the Notification center, [check it out](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/androidautoidrive-latest-bmwone_notification-nomap-sentry-release.apk)!
Let me know if there's any weird behaviors (perhaps the car starts ignoring clicks from this screen after a few minutes, or it opens the wrong message)

**Comment by jezikk82** [comment]
Hi, I heavly tested this feature for last 2 days and can confirm that it works great.

I'd like to see 2 small enhansments:
- choose which app can forward notifications to system Notification Center
- customisation of the icon presented in car and link it to apps.

App selection can be done similar way SMS&notification app mentioned here.

Great work 👍

**Comment by hufman** [comment]
Thanks so much for testing!
Currently it uses the same logic for new notifications for the popup, the notification sound, and this notification center. #119 is tracking a UI to customize the behavior, but I do hope to improve the heuristics to make it pick the correct behavior automatically. Can you add feedback to #119 about what apps and notification types you want different behavior for?
The icon, however, can't be changed: It's hardcoded to the icon pack for the BMW Connected app that I'm logging in with, and the envelope icon seems to make the most sense for this purpose. 
![image](https://user-images.githubusercontent.com/1592375/110876218-eb9e0980-828b-11eb-90de-a3669e1f430e.png)

**Comment by jezikk82** [comment]
I haven't notice the sound when notification came to Notification Center - have to check it. 

About icons, it's interesting because I see in my I drive with Office functions couple of icons related to notifications, try to catch them by photo to show, but it's for missed call, 2 different for SMS and Mail, Calendar events, other related to car's status, etc.

**Comment by hufman** [comment]
Indeed, the app itself would play a notification sound (if enabled) through the Bluetooth connection, and so it will only be audible if the car is also playing music from a Bluetooth source. It is not directly because of the Notification Center.

Different functions in the car are essentially their own apps, and they each have their own icon packs to use when they post a message to the Notification Center. The NotificationEvent that I trigger through the API only accepts an Image ID, and so I have to point to an existing icon from the icon pack that I upload to the car when connecting. This icon pack is cryptographically signed by BMW, and can't be altered to include new icons.

**Comment by jezikk82** [comment]
Perhaps you can look for "office app" that shows lot of different notifications in car.

**Comment by hufman** [comment]
I am always on the hunt to collect more car apps! Different apps possibly allow for extra functionality, as I'm discovering with Connected's popup and Notification Center abilities. I think I have all of the official Android apps (Connected, SmartThings, iHeartRadio, Pandora, Spotify), but let me know if you find any others!
If you don't mind, could you post a picture or two about some of the entries you see in your Notification Center? I've seen the car status ones and for SMS and missed calls, but I haven't seen any Mail or Calendar events, and I'm curious how those are coming through.

**Comment by HaivanJV** [comment]
HI Hufman. I've been testing this build. A few points I want to send across.

- The notification pops up in full screen in the car, however the space taken by the text is only a fraction of it and it is truncated the same way as when it is displayed in the normal Notification App main menu (with the three dots). It would be nice if the full screen pop up could display a bigger portion of the notification text (if not all), similarly to when you expand a notification on the phone without opening it.
- For some reasons, pictures where not previewed and this time not even by opening the message (in my test a WhatsApp message). This was instead featured on the normal notification app.

Let me know if you need a picture and I will try to document this behaviour

**Comment by hufman** [comment]
Thank you so much for testing! It's interesting that your text is cut off with dots, my car (Mini ID5) just fades off at the edge.
I tried a few options but was unable to make the text box any longer or wrap onto multiple lines in the new popup view.
The popup view doesn't have a good image widget, but the new popup does include a button to open up the message in the full view like before.

**Comment by HaivanJV** [comment]
Now that you mention, I am not sure if it was with the three dots or with fading, but I remember the truncation.
I have BMW ID6. I'll try to re-test opening a picture via the popup.
